import type { PublicHousingSnapshotV1 } from '../api/snapshotPublicHousingRepository.ts'

export const MINIMAL_PUBLIC_HOUSING_SNAPSHOT = {
  version: 1,
  complexListItems: [
    {
      complexId: 17,
      thumbnailImageUrl: null,
      regionName: '서울특별시 중구',
      name: '서울가람 행복주택',
      rentalType: 'HAPPY_HOUSING',
      agency: { code: 'LH', name: '한국토지주택공사' },
      exclusiveAreaMin: 0,
      exclusiveAreaMax: 44.87,
      depositMin: 0,
      depositMax: null,
      monthlyRentMin: 200_000,
      monthlyRentMax: null,
      representativeAnnouncement: {
        announcementId: 201,
        publicationType: 'ORIGINAL',
        applicationStatus: 'APPLYING',
        applicationEndAt: '2026-08-30',
        dDay: 0,
      },
    },
  ],
  mapComplexItems: [
    {
      complexId: 17,
      name: '서울가람 행복주택',
      latitude: 37.5666,
      longitude: 126.9784,
      rentalType: 'HAPPY_HOUSING',
      agency: { code: 'LH', name: '한국토지주택공사' },
      exclusiveAreaMin: 0,
      exclusiveAreaMax: 44.87,
      depositMin: 0,
      depositMax: null,
      monthlyRentMin: 200_000,
      monthlyRentMax: null,
    },
  ],
  complexDetails: [
    {
      complexId: 17,
      name: '서울가람 행복주택',
      rentalType: 'HAPPY_HOUSING',
      agency: { code: 'LH', name: '한국토지주택공사' },
      address: {
        regionName: '서울특별시 중구',
        roadAddress: '서울특별시 중구 세종대로 110',
        latitude: 37.5666,
        longitude: 126.9784,
      },
      completionDate: null,
      buildingType: 'APARTMENT',
      hasElevator: false,
      heatingType: null,
      corridorType: 'STAIR',
      moveOutCountLastYear: 0,
      totalHouseholdCount: 100,
      totalParkingCount: 0,
      images: [],
      overviewImageUrl: null,
      housingTypes: [
        {
          housingTypeId: 301,
          name: '36A',
          exclusiveArea: 0,
          supplyArea: null,
          floorPlanImageUrl: null,
          floorPlan3dImageUrl: null,
          isDuplex: false,
          maintenanceFee: 0,
          currentSupplyConditions: [
            {
              target: '청년',
              deposit: 0,
              monthlyRent: null,
              convertibleDeposit: null,
            },
          ],
        },
      ],
      currentAnnouncements: [
        {
          announcementId: 201,
          title: '서울 청년 행복주택 입주자 모집',
          publicationType: 'ORIGINAL',
          applicationStatus: 'APPLYING',
          targets: ['청년'],
          applicationStartAt: '2026-08-28',
          applicationEndAt: '2026-08-30',
          dDay: 0,
          actualCompetitionRate: 0,
        },
      ],
    },
  ],
  announcementListItems: [
    {
      announcementId: 201,
      publicationType: 'ORIGINAL',
      applicationStatus: 'APPLYING',
      rentalType: 'HAPPY_HOUSING',
      recruitmentType: 'NEW',
      title: '서울 청년 행복주택 입주자 모집',
      regionNames: ['서울특별시 중구'],
      publishedAt: null,
      applicationStartAt: '2026-08-28',
      applicationEndAt: '2026-08-30',
      dDay: 0,
      viewCount: 0,
      supplyComplexCount: 1,
      supplyHouseholdCount: 0,
      agency: { code: 'LH', name: '한국토지주택공사' },
      actualCompetitionRate: 0,
      predictedCompetitionRate: null,
      thumbnailImageUrl: null,
    },
  ],
  announcementDetails: [
    {
      announcementId: 201,
      publicationType: 'ORIGINAL',
      correctionOrCancellationReason: null,
      applicationStatus: 'APPLYING',
      rentalType: 'HAPPY_HOUSING',
      recruitmentType: 'NEW',
      title: '서울 청년 행복주택 입주자 모집',
      regionNames: ['서울특별시 중구'],
      agency: { code: 'LH', name: '한국토지주택공사' },
      publishedAt: null,
      applicationStartAt: '2026-08-28',
      applicationEndAt: '2026-08-30',
      dDay: 0,
      winnerAnnouncementAt: null,
      viewCount: 0,
      targets: ['청년'],
      supplyComplexCount: 1,
      supplyHouseholdCount: 0,
      documentLinkUrl: null,
      receptionPlaces: [
        {
          name: null,
          method: 'ONLINE',
          address: null,
          phoneNumber: null,
          url: 'https://apply.lh.or.kr',
        },
      ],
      schedules: [
        {
          scheduleId: 501,
          type: 'APPLICATION',
          name: null,
          startAt: '2026-08-28T09:00',
          endAt: null,
        },
      ],
      attachments: [],
      supplyRows: [
        {
          supplyRowId: 401,
          sourceComplexName: '서울가람 행복주택',
          sourceHousingTypeName: '36A',
          complex: {
            complexId: 17,
            name: '서울가람 행복주택',
            address: '서울특별시 중구 세종대로 110',
            totalHouseholdCount: 100,
            overviewImageUrl: null,
          },
          housingType: {
            housingTypeId: 301,
            name: '36A',
            exclusiveArea: 0,
            supplyArea: null,
            floorPlanImageUrl: null,
            floorPlan3dImageUrl: null,
          },
          occupancyExpectedYearMonth: null,
          supplyType: 'NEW',
          totalSupplyHouseholdCount: 0,
          targets: [
            {
              supplyTargetId: 601,
              target: '청년',
              priority: null,
              supplyHouseholdCount: 0,
              waitlistCount: null,
              deposit: 0,
              monthlyRent: null,
              convertibleDeposit: null,
              applicationCondition: null,
            },
          ],
        },
      ],
      competition: { actualRate: 0, predictedRate: null },
    },
  ],
} satisfies PublicHousingSnapshotV1
