-- Initial schema for a new, empty PostgreSQL database.
-- Source: production schema-only snapshot, existing SQL changes, and constraint reconciliation.
-- Existing databases use the separate V20260922_01 migration after an explicit baseline at 20260922.00.

--
-- PostgreSQL database dump
--


-- Dumped from database version 17.11
-- Dumped by pg_dump version 17.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admin_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin_accounts (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    login_identifier character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    CONSTRAINT admin_accounts_role_check CHECK (((role)::text = 'ADMIN'::text))
);


--
-- Name: admin_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.admin_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admin_authentication_audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin_authentication_audit_logs (
    id bigint NOT NULL,
    action character varying(255) NOT NULL,
    login_identifier character varying(255) NOT NULL,
    occurred_at timestamp(6) without time zone NOT NULL,
    request_trace_id character varying(255) NOT NULL,
    result character varying(255) NOT NULL,
    CONSTRAINT admin_authentication_audit_logs_action_check CHECK (((action)::text = ANY ((ARRAY['LOGIN'::character varying, 'LOGOUT'::character varying])::text[]))),
    CONSTRAINT admin_authentication_audit_logs_result_check CHECK (((result)::text = ANY ((ARRAY['SUCCESS'::character varying, 'FAILURE'::character varying])::text[])))
);


--
-- Name: admin_authentication_audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.admin_authentication_audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_authentication_audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: announcement_attachments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.announcement_attachments (
    id bigint NOT NULL,
    display_order integer NOT NULL,
    file_name character varying(255) NOT NULL,
    file_type character varying(255) NOT NULL,
    file_url character varying(255) NOT NULL,
    source_attachment_identifier character varying(255),
    announcement_id bigint NOT NULL,
    CONSTRAINT announcement_attachments_file_type_check CHECK (((file_type)::text = ANY ((ARRAY['공고문'::character varying, 'ANNOUNCEMENT'::character varying, '정정공고'::character varying, 'CORRECTION'::character varying, '취소공고'::character varying, 'CANCELLATION'::character varying, '참고자료'::character varying, 'REFERENCE'::character varying, '기타'::character varying, 'ETC'::character varying])::text[])))
);


--
-- Name: announcement_attachments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.announcement_attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.announcement_attachments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: announcement_schedules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.announcement_schedules (
    id bigint NOT NULL,
    display_order integer NOT NULL,
    end_at timestamp(6) without time zone NOT NULL,
    name character varying(255) NOT NULL,
    schedule_type character varying(255) NOT NULL,
    source_schedule_identifier character varying(255),
    start_at timestamp(6) without time zone NOT NULL,
    announcement_id bigint NOT NULL,
    CONSTRAINT announcement_schedules_schedule_type_check CHECK (((schedule_type)::text = ANY ((ARRAY['접수'::character varying, 'APPLICATION'::character varying, '서류제출'::character varying, 'DOCUMENT_SUBMISSION'::character varying, '당첨자발표'::character varying, 'WINNER_ANNOUNCEMENT'::character varying, '계약'::character varying, 'CONTRACT'::character varying, '입주'::character varying, 'MOVE_IN'::character varying, '기타'::character varying, 'ETC'::character varying])::text[])))
);


--
-- Name: announcement_schedules_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.announcement_schedules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.announcement_schedules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: announcements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.announcements (
    id bigint NOT NULL,
    actual_competition_rate numeric(12,4),
    application_end_date date NOT NULL,
    application_start_date date NOT NULL,
    correction_cancellation_reason character varying(255),
    lh_pan_id character varying(255),
    name character varying(255) NOT NULL,
    original_url character varying(255) NOT NULL,
    posted_date date NOT NULL,
    predicted_competition_rate numeric(12,4),
    previous_source_announcement_identifier character varying(255),
    provider character varying(255) NOT NULL,
    reception_address character varying(255),
    reception_contact character varying(255),
    reception_method character varying(255),
    reception_place_name character varying(255),
    reception_url character varying(255),
    recruitment_type character varying(255) NOT NULL,
    source_announcement_identifier character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    supply_type character varying(255) NOT NULL,
    view_count bigint NOT NULL,
    winner_announcement_date date NOT NULL,
    previous_announcement_id bigint,
    CONSTRAINT announcements_provider_check CHECK (((provider)::text = ANY ((ARRAY['한국토지주택공사'::character varying, 'LH'::character varying, '서울주택도시공사'::character varying, 'SH'::character varying, '경기주택도시공사'::character varying, 'GH'::character varying, '기타'::character varying, 'ETC'::character varying])::text[]))),
    CONSTRAINT announcements_reception_method_check CHECK (((reception_method)::text = ANY ((ARRAY['인터넷'::character varying, 'ONLINE'::character varying, '현장'::character varying, 'VISIT'::character varying, '우편'::character varying, 'MAIL'::character varying, '기타'::character varying, 'ETC'::character varying])::text[]))),
    CONSTRAINT announcements_recruitment_type_check CHECK (((recruitment_type)::text = ANY ((ARRAY['신규모집'::character varying, 'NEW'::character varying, '예비입주자'::character varying, 'WAITLIST'::character varying, '기타'::character varying, 'ETC'::character varying])::text[]))),
    CONSTRAINT announcements_status_check CHECK (((status)::text = ANY ((ARRAY['원공고'::character varying, 'ORIGINAL'::character varying, '정정공고'::character varying, 'CORRECTION'::character varying, '취소공고'::character varying, 'CANCELLATION'::character varying])::text[]))),
    CONSTRAINT announcements_supply_type_check CHECK (((supply_type)::text = ANY ((ARRAY['행복주택'::character varying, 'HAPPY_HOUSING'::character varying, '국민임대'::character varying, 'NATIONAL_RENTAL'::character varying, '영구임대'::character varying, 'PERMANENT_RENTAL'::character varying, '50년공공임대'::character varying, 'PUBLIC_RENTAL_50Y'::character varying, '통합공공임대'::character varying, 'INTEGRATED_PUBLIC_RENTAL'::character varying, '재개발임대'::character varying, 'REDEVELOPMENT_RENTAL'::character varying, '기타'::character varying, 'ETC'::character varying])::text[])))
);


--
-- Name: announcements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.announcements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.announcements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: data_pipeline_execution_completed_steps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.data_pipeline_execution_completed_steps (
    data_pipeline_execution_id bigint NOT NULL,
    completed_step character varying(60) NOT NULL,
    step_order integer NOT NULL,
    completed_report text,
    CONSTRAINT data_pipeline_execution_completed_steps_completed_step_check CHECK (((completed_step)::text = ANY ((ARRAY['COLLECT_MYHOME_COMPLEXES'::character varying, 'COLLECT_LH_LEASE_CATALOG'::character varying, 'MAP_MYHOME_COMPLEXES'::character varying, 'ENRICH_LH_HOUSING_TYPE_HOUSEHOLDS'::character varying, 'COLLECT_MYHOME_ANNOUNCEMENTS'::character varying, 'COLLECT_LH_ANNOUNCEMENT_SUPPLIES'::character varying, 'COLLECT_LH_ANNOUNCEMENT_DETAILS'::character varying, 'MAP_MYHOME_ANNOUNCEMENTS'::character varying, 'ENRICH_LH_ANNOUNCEMENTS'::character varying])::text[]))),
    CONSTRAINT data_pipeline_execution_completed_steps_step_order_check CHECK ((step_order >= 0))
);


--
-- Name: data_pipeline_execution_partial_failures; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.data_pipeline_execution_partial_failures (
    data_pipeline_execution_id bigint NOT NULL,
    partial_failure_report text NOT NULL,
    partially_failed_step character varying(60) NOT NULL,
    step_order integer NOT NULL,
    CONSTRAINT data_pipeline_execution_partial_fai_partially_failed_step_check CHECK (((partially_failed_step)::text = ANY ((ARRAY['COLLECT_MYHOME_COMPLEXES'::character varying, 'COLLECT_LH_LEASE_CATALOG'::character varying, 'MAP_MYHOME_COMPLEXES'::character varying, 'ENRICH_LH_HOUSING_TYPE_HOUSEHOLDS'::character varying, 'COLLECT_MYHOME_ANNOUNCEMENTS'::character varying, 'COLLECT_LH_ANNOUNCEMENT_SUPPLIES'::character varying, 'COLLECT_LH_ANNOUNCEMENT_DETAILS'::character varying, 'MAP_MYHOME_ANNOUNCEMENTS'::character varying, 'ENRICH_LH_ANNOUNCEMENTS'::character varying])::text[]))),
    CONSTRAINT data_pipeline_execution_partial_failures_step_order_check CHECK ((step_order >= 0))
);


--
-- Name: data_pipeline_execution_skipped_steps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.data_pipeline_execution_skipped_steps (
    data_pipeline_execution_id bigint NOT NULL,
    skip_reason character varying(500) NOT NULL,
    skip_server_response text,
    skipped_step character varying(60) NOT NULL,
    step_order integer NOT NULL,
    CONSTRAINT data_pipeline_execution_skipped_steps_skipped_step_check CHECK (((skipped_step)::text = ANY ((ARRAY['COLLECT_MYHOME_COMPLEXES'::character varying, 'COLLECT_LH_LEASE_CATALOG'::character varying, 'MAP_MYHOME_COMPLEXES'::character varying, 'ENRICH_LH_HOUSING_TYPE_HOUSEHOLDS'::character varying, 'COLLECT_MYHOME_ANNOUNCEMENTS'::character varying, 'COLLECT_LH_ANNOUNCEMENT_SUPPLIES'::character varying, 'COLLECT_LH_ANNOUNCEMENT_DETAILS'::character varying, 'MAP_MYHOME_ANNOUNCEMENTS'::character varying, 'ENRICH_LH_ANNOUNCEMENTS'::character varying])::text[]))),
    CONSTRAINT data_pipeline_execution_skipped_steps_step_order_check CHECK ((step_order >= 0))
);


--
-- Name: data_pipeline_executions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.data_pipeline_executions (
    id bigint NOT NULL,
    current_step character varying(60),
    execution_id uuid NOT NULL,
    failed_step character varying(60),
    failure_message character varying(500),
    failure_server_response text,
    finished_at timestamp(6) with time zone,
    heartbeat_at timestamp(6) with time zone NOT NULL,
    started_at timestamp(6) with time zone NOT NULL,
    status character varying(20) NOT NULL,
    type character varying(40) NOT NULL,
    CONSTRAINT data_pipeline_executions_current_step_check CHECK (((current_step)::text = ANY ((ARRAY['COLLECT_MYHOME_COMPLEXES'::character varying, 'COLLECT_LH_LEASE_CATALOG'::character varying, 'MAP_MYHOME_COMPLEXES'::character varying, 'ENRICH_LH_HOUSING_TYPE_HOUSEHOLDS'::character varying, 'COLLECT_MYHOME_ANNOUNCEMENTS'::character varying, 'COLLECT_LH_ANNOUNCEMENT_SUPPLIES'::character varying, 'COLLECT_LH_ANNOUNCEMENT_DETAILS'::character varying, 'MAP_MYHOME_ANNOUNCEMENTS'::character varying, 'ENRICH_LH_ANNOUNCEMENTS'::character varying])::text[]))),
    CONSTRAINT data_pipeline_executions_failed_step_check CHECK (((failed_step)::text = ANY ((ARRAY['COLLECT_MYHOME_COMPLEXES'::character varying, 'COLLECT_LH_LEASE_CATALOG'::character varying, 'MAP_MYHOME_COMPLEXES'::character varying, 'ENRICH_LH_HOUSING_TYPE_HOUSEHOLDS'::character varying, 'COLLECT_MYHOME_ANNOUNCEMENTS'::character varying, 'COLLECT_LH_ANNOUNCEMENT_SUPPLIES'::character varying, 'COLLECT_LH_ANNOUNCEMENT_DETAILS'::character varying, 'MAP_MYHOME_ANNOUNCEMENTS'::character varying, 'ENRICH_LH_ANNOUNCEMENTS'::character varying])::text[]))),
    CONSTRAINT data_pipeline_executions_status_check CHECK (((status)::text = ANY ((ARRAY['IDLE'::character varying, 'RUNNING'::character varying, 'COMPLETED'::character varying, 'COMPLETED_WITH_SKIPS'::character varying, 'FAILED'::character varying])::text[]))),
    CONSTRAINT data_pipeline_executions_type_check CHECK (((type)::text = ANY ((ARRAY['COMPLEX_COLLECTION'::character varying, 'COMPLEX_REFINEMENT'::character varying, 'ANNOUNCEMENT_COLLECTION'::character varying, 'ANNOUNCEMENT_REFINEMENT'::character varying])::text[])))
);


--
-- Name: data_pipeline_executions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.data_pipeline_executions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.data_pipeline_executions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: external_data_collection_failures; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.external_data_collection_failures (
    id bigint NOT NULL,
    attempt_count integer DEFAULT 1 NOT NULL,
    error_type character varying(120) NOT NULL,
    occurred_at timestamp(6) with time zone NOT NULL,
    reason character varying(1000) NOT NULL,
    request_description character varying(2000) NOT NULL,
    resolved_at timestamp(6) with time zone,
    source character varying(40) NOT NULL,
    status character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    first_execution_id uuid,
    last_execution_id uuid,
    last_occurred_at timestamp(6) with time zone NOT NULL,
    occurrence_count integer NOT NULL,
    recurrence_count integer NOT NULL,
    resolved_execution_id uuid,
    CONSTRAINT external_data_collection_failures_source_check CHECK (((source)::text = ANY ((ARRAY['MYHOME_COMPLEX'::character varying, 'MYHOME_ANNOUNCEMENT'::character varying, 'LH_LEASE_CATALOG'::character varying, 'LH_ANNOUNCEMENT_DETAIL'::character varying, 'LH_ANNOUNCEMENT_SUPPLY'::character varying])::text[]))),
    CONSTRAINT external_data_collection_failures_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'RESOLVED'::character varying, 'SKIPPED'::character varying])::text[])))
);


--
-- Name: external_data_collection_failures_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.external_data_collection_failures ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.external_data_collection_failures_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: favorite_announcements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.favorite_announcements (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    announcement_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: favorite_announcements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.favorite_announcements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favorite_announcements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: favorite_housing_complexes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.favorite_housing_complexes (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    housing_complex_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: favorite_housing_complexes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.favorite_housing_complexes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favorite_housing_complexes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: favorite_regions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.favorite_regions (
    id bigint NOT NULL,
    city_county_district_code character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    province_code character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: favorite_regions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.favorite_regions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favorite_regions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: housing_complexes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.housing_complexes (
    id bigint NOT NULL,
    city_county_district_code character varying(255) NOT NULL,
    latitude numeric(9,6) NOT NULL,
    legal_dong_code character varying(255) NOT NULL,
    longitude numeric(10,6) NOT NULL,
    pnu character varying(255) NOT NULL,
    province_code character varying(255) NOT NULL,
    road_address character varying(255) NOT NULL,
    completion_date date,
    corridor_type character varying(255),
    elevator_installed boolean,
    heating_type character varying(255),
    housing_type character varying(255),
    image_url character varying(255),
    name character varying(255) NOT NULL,
    parking_space_count integer NOT NULL,
    provider character varying(255) NOT NULL,
    recent_one_year_move_out_count integer,
    source_complex_identifier character varying(255) NOT NULL,
    supply_type character varying(255) NOT NULL,
    total_household_count integer NOT NULL
);


--
-- Name: housing_complexes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.housing_complexes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.housing_complexes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: housing_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.housing_types (
    id bigint NOT NULL,
    duplex boolean,
    exclusive_area numeric(10,4) NOT NULL,
    floor_plan_url character varying(255),
    maintenance_fee numeric(38,2),
    name character varying(255) NOT NULL,
    source_housing_type_identifier character varying(500),
    supply_area numeric(10,4),
    total_household_count integer,
    housing_complex_id bigint NOT NULL
);


--
-- Name: housing_types_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.housing_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.housing_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lh_announcement_collection_checkpoints; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lh_announcement_collection_checkpoints (
    id bigint NOT NULL,
    completed_at timestamp(6) with time zone NOT NULL,
    pan_id character varying(100) NOT NULL,
    request_description character varying(2000) NOT NULL,
    request_hash character varying(64) NOT NULL,
    source character varying(40) NOT NULL,
    source_announcement_key character varying(500) NOT NULL,
    CONSTRAINT lh_announcement_collection_checkpoints_source_check CHECK (((source)::text = ANY ((ARRAY['MYHOME_COMPLEX'::character varying, 'MYHOME_ANNOUNCEMENT'::character varying, 'LH_LEASE_CATALOG'::character varying, 'LH_ANNOUNCEMENT_DETAIL'::character varying, 'LH_ANNOUNCEMENT_SUPPLY'::character varying])::text[])))
);


--
-- Name: lh_announcement_collection_checkpoints_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lh_announcement_collection_checkpoints ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lh_announcement_collection_checkpoints_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lh_announcement_collection_links; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lh_announcement_collection_links (
    id bigint NOT NULL,
    completed_at timestamp(6) with time zone NOT NULL,
    pan_id character varying(100) NOT NULL,
    request_description character varying(2000) NOT NULL,
    request_hash character varying(64) NOT NULL,
    source character varying(40) NOT NULL,
    source_announcement_key character varying(500) NOT NULL,
    CONSTRAINT lh_announcement_collection_links_source_check CHECK (((source)::text = ANY ((ARRAY['MYHOME_COMPLEX'::character varying, 'MYHOME_ANNOUNCEMENT'::character varying, 'LH_LEASE_CATALOG'::character varying, 'LH_ANNOUNCEMENT_DETAIL'::character varying, 'LH_ANNOUNCEMENT_SUPPLY'::character varying])::text[])))
);


--
-- Name: lh_announcement_collection_links_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lh_announcement_collection_links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lh_announcement_collection_links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lh_announcement_detail_source; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lh_announcement_detail_source (
    id bigint NOT NULL,
    address character varying(255),
    application_period character varying(255),
    attachment_complex_name character varying(255),
    collected_at timestamp(6) with time zone,
    complex_name character varying(255),
    contract_begin_date character varying(255),
    contract_end_date character varying(255),
    correction_reason character varying(4000),
    dataset_type character varying(255),
    detail_address character varying(255),
    document_submission_begin_date character varying(255),
    document_submission_end_date character varying(255),
    document_target_announcement_date character varying(255),
    etc_contents character varying(4000),
    exclusive_area_range character varying(255),
    expected_move_in_year_month character varying(255),
    guidance_text character varying(4000),
    heating_description character varying(255),
    kind character varying(255),
    name character varying(255),
    operation_begin character varying(255),
    operation_end character varying(255),
    pan_id character varying(255),
    phone character varying(255),
    reception_address character varying(255),
    reception_detail_address character varying(255),
    reception_guidance character varying(4000),
    source_order integer,
    total_unit_count character varying(255),
    url character varying(1000)
);


--
-- Name: lh_announcement_detail_source_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lh_announcement_detail_source ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lh_announcement_detail_source_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lh_announcement_enrichment_failures; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lh_announcement_enrichment_failures (
    id bigint NOT NULL,
    detail character varying(1000) NOT NULL,
    occurred_at timestamp(6) with time zone NOT NULL,
    pan_id character varying(255),
    reason character varying(50) NOT NULL,
    source_announcement_identifier character varying(255),
    source_key character varying(500) NOT NULL,
    first_execution_id uuid,
    last_execution_id uuid,
    last_resolved_at timestamp(6) with time zone,
    last_resolved_execution_id uuid,
    CONSTRAINT lh_announcement_enrichment_failures_reason_check CHECK (((reason)::text = ANY ((ARRAY['ANNOUNCEMENT_NOT_FOUND'::character varying, 'PAN_ID_NOT_FOUND'::character varying, 'LH_DETAIL_SOURCE_NOT_FOUND'::character varying, 'LH_SUPPLY_SOURCE_NOT_FOUND'::character varying, 'UNSUPPORTED_SUPPLY_TYPE'::character varying, 'INVALID_VALUE'::character varying, 'COMPLEX_NOT_FOUND'::character varying, 'AMBIGUOUS_COMPLEX'::character varying, 'HOUSING_TYPE_NOT_FOUND'::character varying, 'AMBIGUOUS_HOUSING_TYPE'::character varying])::text[])))
);


--
-- Name: lh_announcement_enrichment_failures_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lh_announcement_enrichment_failures ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lh_announcement_enrichment_failures_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lh_announcement_supply_source; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lh_announcement_supply_source (
    id bigint NOT NULL,
    collected_at timestamp(6) with time zone,
    complex_label character varying(255),
    deposit_text character varying(255),
    exclusive_area character varying(255),
    monthly_rent_text character varying(255),
    pan_id character varying(255),
    source_order integer,
    supplied_unit_count character varying(255),
    supply_area character varying(255),
    total_unit_count character varying(255),
    type_name character varying(255)
);


--
-- Name: lh_announcement_supply_source_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lh_announcement_supply_source ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lh_announcement_supply_source_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lh_catalog_source; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lh_catalog_source (
    id bigint NOT NULL,
    area_name character varying(255),
    collected_at timestamp(6) with time zone,
    complex_label character varying(255),
    complex_total_unit_count character varying(255),
    deposit_text character varying(255),
    exclusive_area character varying(255),
    monthly_rent_text character varying(255),
    source_order integer,
    supply_type_name character varying(255),
    total_unit_count character varying(255)
);


--
-- Name: lh_catalog_source_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lh_catalog_source ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lh_catalog_source_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lh_household_enrichment_failures; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lh_household_enrichment_failures (
    id bigint NOT NULL,
    area_name character varying(200),
    complex_name character varying(500),
    detail character varying(1000) NOT NULL,
    first_execution_id uuid,
    last_execution_id uuid,
    last_occurred_at timestamp(6) with time zone NOT NULL,
    last_resolved_at timestamp(6) with time zone,
    last_resolved_execution_id uuid,
    occurred_at timestamp(6) with time zone NOT NULL,
    occurrence_count integer NOT NULL,
    reason character varying(40) NOT NULL,
    recurrence_count integer NOT NULL,
    source_key character varying(500) NOT NULL,
    status character varying(20) NOT NULL,
    supply_type_name character varying(200),
    CONSTRAINT lh_household_enrichment_failures_reason_check CHECK (((reason)::text = ANY ((ARRAY['INVALID_SOURCE'::character varying, 'COMPLEX_NOT_FOUND'::character varying, 'AMBIGUOUS_COMPLEX'::character varying, 'DUPLICATE_TARGET_COMPLEX'::character varying])::text[]))),
    CONSTRAINT lh_household_enrichment_failures_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'RESOLVED'::character varying])::text[])))
);


--
-- Name: lh_household_enrichment_failures_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lh_household_enrichment_failures ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lh_household_enrichment_failures_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: myhome_announcement_mapping_failures; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.myhome_announcement_mapping_failures (
    id bigint NOT NULL,
    detail character varying(1000) NOT NULL,
    occurred_at timestamp(6) with time zone NOT NULL,
    reason character varying(50) NOT NULL,
    source_announcement_identifier character varying(255),
    source_house_serial_number integer,
    source_key character varying(500) NOT NULL,
    first_execution_id uuid,
    last_execution_id uuid,
    last_resolved_at timestamp(6) with time zone,
    last_resolved_execution_id uuid,
    CONSTRAINT myhome_announcement_mapping_failures_reason_check CHECK (((reason)::text = ANY ((ARRAY['MISSING_REQUIRED_VALUE'::character varying, 'INVALID_VALUE'::character varying, 'CONFLICTING_SOURCE_VALUE'::character varying, 'PREVIOUS_ANNOUNCEMENT_NOT_FOUND'::character varying, 'CYCLIC_ANNOUNCEMENT_REVISION'::character varying, 'COMPLEX_NOT_FOUND'::character varying, 'AMBIGUOUS_COMPLEX'::character varying, 'HOUSING_TYPE_NOT_FOUND'::character varying, 'AMBIGUOUS_HOUSING_TYPE'::character varying])::text[])))
);


--
-- Name: myhome_announcement_mapping_failures_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.myhome_announcement_mapping_failures ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.myhome_announcement_mapping_failures_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: myhome_announcement_source; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.myhome_announcement_source (
    id bigint NOT NULL,
    before_pblanc_id character varying(255),
    begin_de character varying(255),
    brtc_nm character varying(255),
    collected_at timestamp(6) with time zone,
    end_de character varying(255),
    enty bigint,
    full_adres character varying(1000),
    heat_mthd_nm character varying(255),
    house_sn integer,
    house_ty_nm character varying(255),
    hsmp_nm character varying(255),
    mobile_url character varying(2000),
    mt_rntchrg bigint,
    pblanc_id character varying(255),
    pblanc_nm character varying(255),
    pc_url character varying(2000),
    pnu character varying(255),
    przwner_presnatn_de character varying(255),
    rcrit_pblanc_de character varying(255),
    refrn_legaldong_nm character varying(255),
    refrnc character varying(2000),
    rent_gtn bigint,
    rn_code_nm character varying(255),
    signgu_nm character varying(255),
    source_key character varying(500) NOT NULL,
    source_order integer,
    sttus_nm character varying(255),
    sum_suply_co integer,
    suply_instt_nm character varying(255),
    suply_ty_nm character varying(255),
    surlus bigint,
    tot_hshld_co character varying(255),
    url character varying(2000),
    active boolean NOT NULL,
    consecutive_miss_count integer NOT NULL,
    last_seen_run_id character varying(100)
);


--
-- Name: myhome_announcement_source_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.myhome_announcement_source ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.myhome_announcement_source_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: myhome_complex_mapping_candidates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.myhome_complex_mapping_candidates (
    id bigint NOT NULL,
    geocoding_failure_reason character varying(40),
    latitude numeric(9,6),
    longitude numeric(10,6),
    resolved_road_address character varying(500),
    source_complex_identifier character varying(255) NOT NULL,
    source_road_address character varying(500) NOT NULL,
    status character varying(30) NOT NULL,
    CONSTRAINT myhome_complex_mapping_candidate_geocoding_failure_reason_check CHECK (((geocoding_failure_reason)::text = ANY ((ARRAY['INVALID_ADDRESS'::character varying, 'ADDRESS_NOT_FOUND'::character varying, 'AMBIGUOUS_ADDRESS'::character varying, 'COORDINATE_NOT_FOUND'::character varying, 'EXTERNAL_API_ERROR'::character varying, 'COORDINATE_CONVERSION_ERROR'::character varying, 'NOT_CONFIGURED'::character varying])::text[]))),
    CONSTRAINT myhome_complex_mapping_candidates_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'GEOCODED'::character varying, 'GEOCODING_FAILED'::character varying, 'MAPPING_FAILED'::character varying, 'MAPPED'::character varying])::text[])))
);


--
-- Name: myhome_complex_mapping_candidates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.myhome_complex_mapping_candidates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.myhome_complex_mapping_candidates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: myhome_complex_mapping_failures; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.myhome_complex_mapping_failures (
    id bigint NOT NULL,
    detail character varying(1000) NOT NULL,
    occurred_at timestamp(6) with time zone NOT NULL,
    reason character varying(40) NOT NULL,
    source_complex_identifier character varying(255),
    source_key character varying(500) NOT NULL,
    first_execution_id uuid,
    last_execution_id uuid,
    last_resolved_at timestamp(6) with time zone,
    last_resolved_execution_id uuid,
    CONSTRAINT myhome_complex_mapping_failures_reason_check CHECK (((reason)::text = ANY ((ARRAY['MISSING_REQUIRED_VALUE'::character varying, 'INVALID_VALUE'::character varying, 'CONFLICTING_SOURCE_VALUE'::character varying, 'GEOCODING_ERROR'::character varying, 'PERSISTENCE_ERROR'::character varying])::text[])))
);


--
-- Name: myhome_complex_mapping_failures_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.myhome_complex_mapping_failures ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.myhome_complex_mapping_failures_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: myhome_complex_source; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.myhome_complex_source (
    id bigint NOT NULL,
    bass_cnvrs_gtn_lmt bigint,
    bass_mt_rntchrg bigint,
    bass_rent_gtn bigint,
    brtc_code character varying(255),
    brtc_nm character varying(255),
    buld_stle_nm character varying(255),
    collected_at timestamp(6) with time zone,
    compet_de character varying(255),
    elvtr_instl_at_nm character varying(255),
    heat_mthd_detail_nm character varying(255),
    house_ty_nm character varying(255),
    hshld_co integer,
    hsmp_nm character varying(255),
    hsmp_sn bigint,
    instt_nm character varying(255),
    parkng_co integer,
    pnu character varying(255),
    rn_adres character varying(255),
    signgu_code character varying(255),
    signgu_nm character varying(255),
    source_key character varying(500) NOT NULL,
    style_nm character varying(255),
    suply_cmnuse_ar numeric(10,4),
    suply_prvuse_ar numeric(10,4),
    suply_ty_nm character varying(255)
);


--
-- Name: myhome_complex_source_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.myhome_complex_source ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.myhome_complex_source_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: road_address_locations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.road_address_locations (
    building_main_number integer NOT NULL,
    building_sub_number integer NOT NULL,
    entrance_serial character varying(10) NOT NULL,
    road_name_code character varying(12) NOT NULL,
    underground character varying(1) NOT NULL,
    normalized_road_address character varying(500) NOT NULL,
    province_code character varying(2) NOT NULL,
    road_address character varying(500) NOT NULL,
    x numeric(15,6),
    y numeric(15,6)
);


--
-- Name: supply_rows; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.supply_rows (
    id bigint NOT NULL,
    display_order integer NOT NULL,
    expected_move_in_month character varying(255),
    lh_source_supply_row_identifier character varying(255),
    matching_failure_reason character varying(255),
    source_complex_name character varying(255) NOT NULL,
    source_housing_type_name character varying(255) NOT NULL,
    source_supply_row_identifier character varying(255) NOT NULL,
    supply_category character varying(255) NOT NULL,
    supply_pnu character varying(255) NOT NULL,
    total_supply_household_count integer,
    announcement_id bigint NOT NULL,
    housing_complex_id bigint,
    housing_type_id bigint,
    CONSTRAINT supply_rows_supply_category_check CHECK (((supply_category)::text = ANY ((ARRAY['NEW_SUPPLY'::character varying, 'RESUPPLY'::character varying])::text[])))
);


--
-- Name: supply_rows_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.supply_rows ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.supply_rows_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: supply_targets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.supply_targets (
    id bigint NOT NULL,
    application_condition character varying(255),
    converted_deposit numeric(38,2),
    display_order integer NOT NULL,
    monthly_rent numeric(38,2),
    rental_deposit numeric(38,2),
    reserve_count integer,
    source_supply_target_identifier character varying(255),
    supply_household_count integer,
    supply_rank character varying(255),
    target character varying(255) NOT NULL,
    supply_row_id bigint NOT NULL
);


--
-- Name: supply_targets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.supply_targets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.supply_targets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_eligibility_infos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_eligibility_infos (
    user_id bigint NOT NULL,
    basic_living_recipient boolean NOT NULL,
    birth_date date NOT NULL,
    child_count integer NOT NULL,
    current_residence_region character varying(255) NOT NULL,
    disabled boolean NOT NULL,
    employed boolean NOT NULL,
    head_of_household boolean NOT NULL,
    household_average_monthly_income numeric(38,2) NOT NULL,
    household_member_count integer NOT NULL,
    housing_benefit_recipient boolean NOT NULL,
    housing_subscription_account boolean NOT NULL,
    housing_subscription_account_join_date date,
    housing_subscription_payment_count integer,
    marital_status character varying(255) NOT NULL,
    marriage_date date,
    newborn_birth_date date,
    non_homeowner boolean NOT NULL,
    parents_average_monthly_income numeric(38,2) NOT NULL,
    personal_average_monthly_income numeric(38,2) NOT NULL,
    single_parent_family boolean NOT NULL,
    spouse_monthly_income numeric(38,2),
    student boolean NOT NULL,
    total_assets numeric(38,2) NOT NULL,
    vehicle_value numeric(38,2) NOT NULL,
    veteran boolean NOT NULL
);


--
-- Name: user_places; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_places (
    id bigint NOT NULL,
    address character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    latitude numeric(9,6) NOT NULL,
    longitude numeric(10,6) NOT NULL,
    name character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: user_places_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_places ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_places_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    login_identifier character varying(255) NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admin_accounts admin_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_accounts
    ADD CONSTRAINT admin_accounts_pkey PRIMARY KEY (id);


--
-- Name: admin_authentication_audit_logs admin_authentication_audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_authentication_audit_logs
    ADD CONSTRAINT admin_authentication_audit_logs_pkey PRIMARY KEY (id);


--
-- Name: announcement_attachments announcement_attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announcement_attachments
    ADD CONSTRAINT announcement_attachments_pkey PRIMARY KEY (id);


--
-- Name: announcement_schedules announcement_schedules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announcement_schedules
    ADD CONSTRAINT announcement_schedules_pkey PRIMARY KEY (id);


--
-- Name: announcements announcements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announcements
    ADD CONSTRAINT announcements_pkey PRIMARY KEY (id);


--
-- Name: data_pipeline_execution_completed_steps data_pipeline_execution_completed_steps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_pipeline_execution_completed_steps
    ADD CONSTRAINT data_pipeline_execution_completed_steps_pkey PRIMARY KEY (data_pipeline_execution_id, step_order);


--
-- Name: data_pipeline_execution_partial_failures data_pipeline_execution_partial_failures_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_pipeline_execution_partial_failures
    ADD CONSTRAINT data_pipeline_execution_partial_failures_pkey PRIMARY KEY (data_pipeline_execution_id, step_order);


--
-- Name: data_pipeline_execution_skipped_steps data_pipeline_execution_skipped_steps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_pipeline_execution_skipped_steps
    ADD CONSTRAINT data_pipeline_execution_skipped_steps_pkey PRIMARY KEY (data_pipeline_execution_id, step_order);


--
-- Name: data_pipeline_executions data_pipeline_executions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_pipeline_executions
    ADD CONSTRAINT data_pipeline_executions_pkey PRIMARY KEY (id);


--
-- Name: external_data_collection_failures external_data_collection_failures_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.external_data_collection_failures
    ADD CONSTRAINT external_data_collection_failures_pkey PRIMARY KEY (id);


--
-- Name: favorite_announcements favorite_announcements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorite_announcements
    ADD CONSTRAINT favorite_announcements_pkey PRIMARY KEY (id);


--
-- Name: favorite_housing_complexes favorite_housing_complexes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorite_housing_complexes
    ADD CONSTRAINT favorite_housing_complexes_pkey PRIMARY KEY (id);


--
-- Name: favorite_regions favorite_regions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorite_regions
    ADD CONSTRAINT favorite_regions_pkey PRIMARY KEY (id);


--
-- Name: housing_complexes housing_complexes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.housing_complexes
    ADD CONSTRAINT housing_complexes_pkey PRIMARY KEY (id);


--
-- Name: housing_types housing_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.housing_types
    ADD CONSTRAINT housing_types_pkey PRIMARY KEY (id);


--
-- Name: lh_announcement_collection_checkpoints lh_announcement_collection_checkpoints_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lh_announcement_collection_checkpoints
    ADD CONSTRAINT lh_announcement_collection_checkpoints_pkey PRIMARY KEY (id);


--
-- Name: lh_announcement_collection_links lh_announcement_collection_links_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lh_announcement_collection_links
    ADD CONSTRAINT lh_announcement_collection_links_pkey PRIMARY KEY (id);


--
-- Name: lh_announcement_detail_source lh_announcement_detail_source_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lh_announcement_detail_source
    ADD CONSTRAINT lh_announcement_detail_source_pkey PRIMARY KEY (id);


--
-- Name: lh_announcement_enrichment_failures lh_announcement_enrichment_failures_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lh_announcement_enrichment_failures
    ADD CONSTRAINT lh_announcement_enrichment_failures_pkey PRIMARY KEY (id);


--
-- Name: lh_announcement_supply_source lh_announcement_supply_source_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lh_announcement_supply_source
    ADD CONSTRAINT lh_announcement_supply_source_pkey PRIMARY KEY (id);


--
-- Name: lh_catalog_source lh_catalog_source_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lh_catalog_source
    ADD CONSTRAINT lh_catalog_source_pkey PRIMARY KEY (id);


--
-- Name: lh_household_enrichment_failures lh_household_enrichment_failures_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lh_household_enrichment_failures
    ADD CONSTRAINT lh_household_enrichment_failures_pkey PRIMARY KEY (id);


--
-- Name: myhome_announcement_mapping_failures myhome_announcement_mapping_failures_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.myhome_announcement_mapping_failures
    ADD CONSTRAINT myhome_announcement_mapping_failures_pkey PRIMARY KEY (id);


--
-- Name: myhome_announcement_source myhome_announcement_source_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.myhome_announcement_source
    ADD CONSTRAINT myhome_announcement_source_pkey PRIMARY KEY (id);


--
-- Name: myhome_complex_mapping_candidates myhome_complex_mapping_candidates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.myhome_complex_mapping_candidates
    ADD CONSTRAINT myhome_complex_mapping_candidates_pkey PRIMARY KEY (id);


--
-- Name: myhome_complex_mapping_failures myhome_complex_mapping_failures_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.myhome_complex_mapping_failures
    ADD CONSTRAINT myhome_complex_mapping_failures_pkey PRIMARY KEY (id);


--
-- Name: myhome_complex_source myhome_complex_source_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.myhome_complex_source
    ADD CONSTRAINT myhome_complex_source_pkey PRIMARY KEY (id);


--
-- Name: road_address_locations road_address_locations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.road_address_locations
    ADD CONSTRAINT road_address_locations_pkey PRIMARY KEY (building_main_number, building_sub_number, entrance_serial, road_name_code, underground);


--
-- Name: supply_rows supply_rows_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supply_rows
    ADD CONSTRAINT supply_rows_pkey PRIMARY KEY (id);


--
-- Name: supply_targets supply_targets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supply_targets
    ADD CONSTRAINT supply_targets_pkey PRIMARY KEY (id);


--
-- Name: announcements uk3m09khb8b0k0clhuileydcsv5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announcements
    ADD CONSTRAINT uk3m09khb8b0k0clhuileydcsv5 UNIQUE (previous_announcement_id);


--
-- Name: data_pipeline_executions uk5ljly7i72fwdt31qsf3xth50e; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_pipeline_executions
    ADD CONSTRAINT uk5ljly7i72fwdt31qsf3xth50e UNIQUE (execution_id);


--
-- Name: announcements uk_announcement_source_identifier; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announcements
    ADD CONSTRAINT uk_announcement_source_identifier UNIQUE (source_announcement_identifier);


--
-- Name: housing_complexes uk_housing_complex_source_identifier; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.housing_complexes
    ADD CONSTRAINT uk_housing_complex_source_identifier UNIQUE (source_complex_identifier);


--
-- Name: housing_types uk_housing_type_source_identifier; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.housing_types
    ADD CONSTRAINT uk_housing_type_source_identifier UNIQUE (source_housing_type_identifier);


--
-- Name: lh_announcement_collection_links uk_lh_announcement_link_source_announcement; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lh_announcement_collection_links
    ADD CONSTRAINT uk_lh_announcement_link_source_announcement UNIQUE (source, source_announcement_key);


--
-- Name: myhome_complex_mapping_candidates uk_myhome_mapping_candidate_source_identifier; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.myhome_complex_mapping_candidates
    ADD CONSTRAINT uk_myhome_mapping_candidate_source_identifier UNIQUE (source_complex_identifier);


--
-- Name: supply_rows uk_supply_row_source_identifier; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supply_rows
    ADD CONSTRAINT uk_supply_row_source_identifier UNIQUE (source_supply_row_identifier);


--
-- Name: myhome_complex_source uka3ty4dyd599kwtsdwipu9nhh2; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.myhome_complex_source
    ADD CONSTRAINT uka3ty4dyd599kwtsdwipu9nhh2 UNIQUE (source_key);


--
-- Name: myhome_announcement_source ukbb1cr4gqtm6eet5rkqogobs12; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.myhome_announcement_source
    ADD CONSTRAINT ukbb1cr4gqtm6eet5rkqogobs12 UNIQUE (source_key);


--
-- Name: admin_accounts uke21mtyui0evhml1866ucj0xbc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_accounts
    ADD CONSTRAINT uke21mtyui0evhml1866ucj0xbc UNIQUE (login_identifier);


--
-- Name: lh_announcement_collection_checkpoints ukhta4o8jg0r69kplfclu8x7g8j; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lh_announcement_collection_checkpoints
    ADD CONSTRAINT ukhta4o8jg0r69kplfclu8x7g8j UNIQUE (source, request_hash);


--
-- Name: lh_announcement_detail_source ukhvlfwy2ho50pxnjv8kft91qxh; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lh_announcement_detail_source
    ADD CONSTRAINT ukhvlfwy2ho50pxnjv8kft91qxh UNIQUE (pan_id, source_order, dataset_type);


--
-- Name: lh_announcement_supply_source ukmf6m5jqtm9imthkguo0fjqnte; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lh_announcement_supply_source
    ADD CONSTRAINT ukmf6m5jqtm9imthkguo0fjqnte UNIQUE (pan_id, source_order);


--
-- Name: user_eligibility_infos user_eligibility_infos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_eligibility_infos
    ADD CONSTRAINT user_eligibility_infos_pkey PRIMARY KEY (user_id);


--
-- Name: user_places user_places_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_places
    ADD CONSTRAINT user_places_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_announcements_posted_date_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_announcements_posted_date_id ON public.announcements USING btree (posted_date, id);


--
-- Name: idx_data_pipeline_execution_type_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_data_pipeline_execution_type_id ON public.data_pipeline_executions USING btree (type, id);


--
-- Name: idx_lh_announcement_checkpoint_source_pan_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_lh_announcement_checkpoint_source_pan_id ON public.lh_announcement_collection_checkpoints USING btree (source, pan_id);


--
-- Name: idx_lh_announcement_link_source_request_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_lh_announcement_link_source_request_hash ON public.lh_announcement_collection_links USING btree (source, request_hash);


--
-- Name: idx_road_address_location_address; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_road_address_location_address ON public.road_address_locations USING btree (normalized_road_address);


--
-- Name: favorite_housing_complexes fk2prbvtbsi254ekmd1wwgk8cvu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorite_housing_complexes
    ADD CONSTRAINT fk2prbvtbsi254ekmd1wwgk8cvu FOREIGN KEY (housing_complex_id) REFERENCES public.housing_complexes(id);


--
-- Name: data_pipeline_execution_completed_steps fk2s4e5241x5lpiu0a3nfxlgi5a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_pipeline_execution_completed_steps
    ADD CONSTRAINT fk2s4e5241x5lpiu0a3nfxlgi5a FOREIGN KEY (data_pipeline_execution_id) REFERENCES public.data_pipeline_executions(id);


--
-- Name: announcement_attachments fk2u0xwqe39jka66c6uy5lrsxr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announcement_attachments
    ADD CONSTRAINT fk2u0xwqe39jka66c6uy5lrsxr FOREIGN KEY (announcement_id) REFERENCES public.announcements(id);


--
-- Name: supply_rows fk5uh4mbvudrgisrc6cckomhvy8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supply_rows
    ADD CONSTRAINT fk5uh4mbvudrgisrc6cckomhvy8 FOREIGN KEY (announcement_id) REFERENCES public.announcements(id);


--
-- Name: favorite_housing_complexes fk6dw1noo65uep86nbd6m3481l3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorite_housing_complexes
    ADD CONSTRAINT fk6dw1noo65uep86nbd6m3481l3 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: supply_targets fk7uogh8e51lbkdr28p34srw36i; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supply_targets
    ADD CONSTRAINT fk7uogh8e51lbkdr28p34srw36i FOREIGN KEY (supply_row_id) REFERENCES public.supply_rows(id);


--
-- Name: user_places fk8ptymq0h9lppm4yepn10dpeis; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_places
    ADD CONSTRAINT fk8ptymq0h9lppm4yepn10dpeis FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: announcement_schedules fk8qy2cs32yebhsoqsbigd9ec6s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announcement_schedules
    ADD CONSTRAINT fk8qy2cs32yebhsoqsbigd9ec6s FOREIGN KEY (announcement_id) REFERENCES public.announcements(id);


--
-- Name: data_pipeline_execution_partial_failures fkg9sy83s1y1jyh663rg4oaoggs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_pipeline_execution_partial_failures
    ADD CONSTRAINT fkg9sy83s1y1jyh663rg4oaoggs FOREIGN KEY (data_pipeline_execution_id) REFERENCES public.data_pipeline_executions(id);


--
-- Name: supply_rows fkgsxyyiny8j9n9owyaj1ys8o3m; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supply_rows
    ADD CONSTRAINT fkgsxyyiny8j9n9owyaj1ys8o3m FOREIGN KEY (housing_complex_id) REFERENCES public.housing_complexes(id);


--
-- Name: favorite_regions fkhc4auvf7jqkoo93p7gm8ef5cm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorite_regions
    ADD CONSTRAINT fkhc4auvf7jqkoo93p7gm8ef5cm FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: supply_rows fkiryalhdin1t68xe5ijb9k0bxh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supply_rows
    ADD CONSTRAINT fkiryalhdin1t68xe5ijb9k0bxh FOREIGN KEY (housing_type_id) REFERENCES public.housing_types(id);


--
-- Name: announcements fkjc9coks8496kpn0cnulx7w6gi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announcements
    ADD CONSTRAINT fkjc9coks8496kpn0cnulx7w6gi FOREIGN KEY (previous_announcement_id) REFERENCES public.announcements(id);


--
-- Name: housing_types fkm3h3st9e6twixn4gh8n5vx4bx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.housing_types
    ADD CONSTRAINT fkm3h3st9e6twixn4gh8n5vx4bx FOREIGN KEY (housing_complex_id) REFERENCES public.housing_complexes(id);


--
-- Name: favorite_announcements fkr1vmfex7s7mchra6rwr0elrs3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorite_announcements
    ADD CONSTRAINT fkr1vmfex7s7mchra6rwr0elrs3 FOREIGN KEY (announcement_id) REFERENCES public.announcements(id);


--
-- Name: favorite_announcements fkr4l4kc6y2nwp4xfy7rrtk28db; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorite_announcements
    ADD CONSTRAINT fkr4l4kc6y2nwp4xfy7rrtk28db FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: data_pipeline_execution_skipped_steps fksaeynkxd4ypgb3edsup8ni4aw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_pipeline_execution_skipped_steps
    ADD CONSTRAINT fksaeynkxd4ypgb3edsup8ni4aw FOREIGN KEY (data_pipeline_execution_id) REFERENCES public.data_pipeline_executions(id);


--
-- Name: user_eligibility_infos fkss9pjpexsfj0hq56xqv94q0qd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_eligibility_infos
    ADD CONSTRAINT fkss9pjpexsfj0hq56xqv94q0qd FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

SET search_path TO public;

-- Applied state from V20260902_01__add_myhome_announcement_source_lifecycle.sql

ALTER TABLE myhome_announcement_source
    ADD COLUMN IF NOT EXISTS last_seen_run_id VARCHAR(100),
    ADD COLUMN IF NOT EXISTS consecutive_miss_count INTEGER,
    ADD COLUMN IF NOT EXISTS active BOOLEAN;

UPDATE myhome_announcement_source
SET consecutive_miss_count = COALESCE(consecutive_miss_count, 0),
    active = COALESCE(active, TRUE);

ALTER TABLE myhome_announcement_source
    ALTER COLUMN consecutive_miss_count SET DEFAULT 0,
    ALTER COLUMN consecutive_miss_count SET NOT NULL,
    ALTER COLUMN active SET DEFAULT TRUE,
    ALTER COLUMN active SET NOT NULL;

-- Applied state from V20260903_01__create_data_pipeline_executions.sql

CREATE TABLE IF NOT EXISTS data_pipeline_executions (
    id BIGSERIAL PRIMARY KEY,
    execution_id UUID NOT NULL UNIQUE,
    type VARCHAR(40) NOT NULL,
    status VARCHAR(20) NOT NULL,
    current_step VARCHAR(60),
    failed_step VARCHAR(60),
    failure_message VARCHAR(500),
    failure_server_response TEXT,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    heartbeat_at TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at TIMESTAMP WITH TIME ZONE
);

ALTER TABLE data_pipeline_executions
    ADD COLUMN IF NOT EXISTS heartbeat_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE data_pipeline_executions
    ALTER COLUMN type TYPE VARCHAR(40);

UPDATE data_pipeline_executions
SET heartbeat_at = COALESCE(heartbeat_at, started_at);

ALTER TABLE data_pipeline_executions
    ALTER COLUMN heartbeat_at SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_data_pipeline_execution_type_id
    ON data_pipeline_executions (type, id);

CREATE TABLE IF NOT EXISTS data_pipeline_execution_completed_steps (
    data_pipeline_execution_id BIGINT NOT NULL,
    step_order INTEGER NOT NULL,
    completed_step VARCHAR(60) NOT NULL,
    PRIMARY KEY (data_pipeline_execution_id, step_order),
    CONSTRAINT fk_data_pipeline_completed_step_execution
        FOREIGN KEY (data_pipeline_execution_id)
        REFERENCES data_pipeline_executions (id)
        ON DELETE CASCADE
);

-- Applied state from V20260903_02__add_data_pipeline_skipped_steps.sql

CREATE TABLE IF NOT EXISTS data_pipeline_execution_skipped_steps (
    data_pipeline_execution_id BIGINT NOT NULL,
    step_order INTEGER NOT NULL,
    skipped_step VARCHAR(60) NOT NULL,
    skip_reason VARCHAR(500) NOT NULL,
    skip_server_response TEXT,
    PRIMARY KEY (data_pipeline_execution_id, step_order),
    CONSTRAINT fk_data_pipeline_skipped_step_execution
        FOREIGN KEY (data_pipeline_execution_id)
        REFERENCES data_pipeline_executions (id)
        ON DELETE CASCADE
);

-- Applied state from V20260903_03__create_road_address_locations.sql

CREATE TABLE IF NOT EXISTS road_address_locations (
    road_name_code VARCHAR(12) NOT NULL,
    underground VARCHAR(1) NOT NULL,
    building_main_number INTEGER NOT NULL,
    building_sub_number INTEGER NOT NULL,
    entrance_serial VARCHAR(10) NOT NULL,
    province_code VARCHAR(2) NOT NULL,
    road_address VARCHAR(500) NOT NULL,
    normalized_road_address VARCHAR(500) NOT NULL,
    x NUMERIC(15, 6),
    y NUMERIC(15, 6),
    PRIMARY KEY (
        road_name_code,
        underground,
        building_main_number,
        building_sub_number,
        entrance_serial
    ),
    CONSTRAINT ck_road_address_location_coordinate_pair
        CHECK ((x IS NULL AND y IS NULL) OR (x IS NOT NULL AND y IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS idx_road_address_location_address
    ON road_address_locations (normalized_road_address);

-- Applied state from V20260911_01__create_lh_announcement_collection_links.sql
CREATE TABLE IF NOT EXISTS lh_announcement_collection_links (
    id BIGSERIAL PRIMARY KEY,
    source VARCHAR(40) NOT NULL,
    source_announcement_key VARCHAR(500) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    request_description VARCHAR(2000) NOT NULL,
    pan_id VARCHAR(100) NOT NULL,
    completed_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_lh_announcement_link_source_announcement
        UNIQUE (source, source_announcement_key)
);

CREATE INDEX IF NOT EXISTS idx_lh_announcement_link_source_request_hash
    ON lh_announcement_collection_links (source, request_hash);

-- Applied state from V20260917_01__add_lh_link_failure_reasons.sql

ALTER TABLE myhome_announcement_mapping_failures
    DROP CONSTRAINT IF EXISTS myhome_announcement_mapping_failures_reason_check,
    ADD CONSTRAINT myhome_announcement_mapping_failures_reason_check CHECK (reason IN (
        'LH_COLLECTION_REQUEST_UNSUPPORTED',
        'LH_COLLECTION_LINK_NOT_FOUND',
        'LH_COLLECTION_LINK_MISMATCH',
        'LH_SUPPLY_SOURCE_NOT_FOUND',
        'MISSING_REQUIRED_VALUE',
        'INVALID_VALUE',
        'CONFLICTING_SOURCE_VALUE',
        'PREVIOUS_ANNOUNCEMENT_NOT_FOUND',
        'CYCLIC_ANNOUNCEMENT_REVISION',
        'COMPLEX_NOT_FOUND',
        'AMBIGUOUS_COMPLEX',
        'HOUSING_TYPE_NOT_FOUND',
        'AMBIGUOUS_HOUSING_TYPE'
    ));

ALTER TABLE lh_announcement_enrichment_failures
    DROP CONSTRAINT IF EXISTS lh_announcement_enrichment_failures_reason_check,
    ADD CONSTRAINT lh_announcement_enrichment_failures_reason_check CHECK (reason IN (
        'LH_COLLECTION_REQUEST_UNSUPPORTED',
        'LH_COLLECTION_LINK_NOT_FOUND',
        'LH_COLLECTION_LINK_MISMATCH',
        'ANNOUNCEMENT_NOT_FOUND',
        'PAN_ID_NOT_FOUND',
        'LH_DETAIL_SOURCE_NOT_FOUND',
        'LH_SUPPLY_SOURCE_NOT_FOUND',
        'UNSUPPORTED_SUPPLY_TYPE',
        'INVALID_VALUE',
        'COMPLEX_NOT_FOUND',
        'AMBIGUOUS_COMPLEX',
        'HOUSING_TYPE_NOT_FOUND',
        'AMBIGUOUS_HOUSING_TYPE'
    ));

-- Applied state from V20260917_02__add_fixed_term_public_rental_types.sql

ALTER TABLE announcements
    DROP CONSTRAINT IF EXISTS announcements_supply_type_check,
    ADD CONSTRAINT announcements_supply_type_check CHECK (supply_type IN (
        'HAPPY_HOUSING',
        '행복주택',
        'NATIONAL_RENTAL',
        '국민임대',
        'PERMANENT_RENTAL',
        '영구임대',
        'PUBLIC_RENTAL_5Y',
        '5년임대',
        'PUBLIC_RENTAL_10Y',
        '10년임대',
        'PUBLIC_RENTAL_50Y',
        '50년공공임대',
        'INTEGRATED_PUBLIC_RENTAL',
        '통합공공임대',
        'REDEVELOPMENT_RENTAL',
        '재개발임대',
        'ETC',
        '기타'
    ));

-- Applied state from V20260918_01__add_lh_field_ownership.sql

ALTER TABLE announcements
    ADD COLUMN IF NOT EXISTS lh_reception_place_owned BOOLEAN;

UPDATE announcements
SET lh_reception_place_owned = CASE
    WHEN lh_pan_id IS NOT NULL AND reception_method IN ('VISIT', '현장') THEN TRUE
    ELSE FALSE
END
WHERE lh_reception_place_owned IS NULL;

ALTER TABLE announcements
    ALTER COLUMN lh_reception_place_owned SET DEFAULT FALSE,
    ALTER COLUMN lh_reception_place_owned SET NOT NULL;

ALTER TABLE supply_rows
    ADD COLUMN IF NOT EXISTS lh_total_supply_household_count_owned BOOLEAN;

UPDATE supply_rows
SET lh_total_supply_household_count_owned = CASE
    WHEN lh_source_supply_row_identifier IS NOT NULL
        AND total_supply_household_count IS NOT NULL THEN TRUE
    ELSE FALSE
END
WHERE lh_total_supply_household_count_owned IS NULL;

ALTER TABLE supply_rows
    ALTER COLUMN lh_total_supply_household_count_owned SET DEFAULT FALSE,
    ALTER COLUMN lh_total_supply_household_count_owned SET NOT NULL;

-- Applied state from V20260918_02__correct_lh_household_count_ownership.sql

ALTER TABLE supply_rows
    ADD COLUMN IF NOT EXISTS lh_total_supply_household_count_enriched BOOLEAN;

UPDATE supply_rows AS supply_row
SET lh_total_supply_household_count_owned = EXISTS (
    SELECT 1
    FROM lh_announcement_supply_source AS source
    WHERE supply_row.lh_source_supply_row_identifier =
        'LH:' || source.pan_id || ':SUPPLY:' || source.source_order
      AND (
          (
              REPLACE(BTRIM(source.total_unit_count), ',', '') ~ '^[0-9]+$'
              AND REPLACE(BTRIM(source.total_unit_count), ',', '')::NUMERIC =
                  supply_row.total_supply_household_count
          )
          OR (
              REPLACE(BTRIM(source.supplied_unit_count), ',', '') ~ '^[0-9]+$'
              AND REPLACE(BTRIM(source.supplied_unit_count), ',', '')::NUMERIC =
                  supply_row.total_supply_household_count
          )
      )
)
WHERE supply_row.lh_source_supply_row_identifier IS NOT NULL
  AND EXISTS (
      SELECT 1
      FROM lh_announcement_supply_source AS source
      WHERE supply_row.lh_source_supply_row_identifier =
          'LH:' || source.pan_id || ':SUPPLY:' || source.source_order
  );

UPDATE supply_rows AS supply_row
SET lh_total_supply_household_count_enriched = CASE
    WHEN source.id IS NULL THEN supply_row.lh_total_supply_household_count_owned
    ELSE REPLACE(BTRIM(source.total_unit_count), ',', '') ~ '^[0-9]+$'
        AND REPLACE(BTRIM(source.total_unit_count), ',', '')::NUMERIC =
            supply_row.total_supply_household_count
    END
FROM (
    SELECT row.id AS supply_row_id, source.id, source.total_unit_count
    FROM supply_rows AS row
    LEFT JOIN lh_announcement_supply_source AS source
      ON row.lh_source_supply_row_identifier =
          'LH:' || source.pan_id || ':SUPPLY:' || source.source_order
) AS source
WHERE supply_row.id = source.supply_row_id
  AND supply_row.lh_total_supply_household_count_enriched IS NULL;

UPDATE supply_rows
SET lh_total_supply_household_count_enriched = FALSE
WHERE lh_total_supply_household_count_enriched IS NULL;

ALTER TABLE supply_rows
    ALTER COLUMN lh_total_supply_household_count_enriched SET DEFAULT FALSE,
    ALTER COLUMN lh_total_supply_household_count_enriched SET NOT NULL;

-- Applied state from V20260919_01__add_data_pipeline_completed_step_reports.sql
ALTER TABLE data_pipeline_execution_completed_steps
    ADD COLUMN IF NOT EXISTS completed_report TEXT;

-- Applied state from V20260919_02__add_data_pipeline_partial_failure_reports.sql
CREATE TABLE IF NOT EXISTS data_pipeline_execution_partial_failures (
    data_pipeline_execution_id BIGINT NOT NULL,
    step_order INTEGER NOT NULL,
    partially_failed_step VARCHAR(60) NOT NULL,
    partial_failure_report TEXT NOT NULL,
    CONSTRAINT pk_data_pipeline_execution_partial_failures
        PRIMARY KEY (data_pipeline_execution_id, step_order),
    CONSTRAINT fk_data_pipeline_execution_partial_failures_execution
        FOREIGN KEY (data_pipeline_execution_id)
            REFERENCES data_pipeline_executions (id)
            ON DELETE CASCADE
);

-- Applied state from V20260919_03__add_ingest_failure_lifecycle.sql

ALTER TABLE myhome_complex_mapping_failures
    ADD COLUMN IF NOT EXISTS last_occurred_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS occurrence_count INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS recurrence_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    ADD COLUMN IF NOT EXISTS last_resolved_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS first_execution_id UUID,
    ADD COLUMN IF NOT EXISTS last_execution_id UUID,
    ADD COLUMN IF NOT EXISTS last_resolved_execution_id UUID;

UPDATE myhome_complex_mapping_failures
SET last_occurred_at = occurred_at
WHERE last_occurred_at IS NULL;

ALTER TABLE myhome_complex_mapping_failures
    ALTER COLUMN last_occurred_at SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN last_occurred_at SET NOT NULL;

ALTER TABLE myhome_announcement_mapping_failures
    ADD COLUMN IF NOT EXISTS last_occurred_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS occurrence_count INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS recurrence_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    ADD COLUMN IF NOT EXISTS last_resolved_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS first_execution_id UUID,
    ADD COLUMN IF NOT EXISTS last_execution_id UUID,
    ADD COLUMN IF NOT EXISTS last_resolved_execution_id UUID;

UPDATE myhome_announcement_mapping_failures
SET last_occurred_at = occurred_at
WHERE last_occurred_at IS NULL;

ALTER TABLE myhome_announcement_mapping_failures
    ALTER COLUMN last_occurred_at SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN last_occurred_at SET NOT NULL;

ALTER TABLE lh_announcement_enrichment_failures
    ADD COLUMN IF NOT EXISTS last_occurred_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS occurrence_count INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS recurrence_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    ADD COLUMN IF NOT EXISTS last_resolved_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS first_execution_id UUID,
    ADD COLUMN IF NOT EXISTS last_execution_id UUID,
    ADD COLUMN IF NOT EXISTS last_resolved_execution_id UUID;

UPDATE lh_announcement_enrichment_failures
SET last_occurred_at = occurred_at
WHERE last_occurred_at IS NULL;

ALTER TABLE lh_announcement_enrichment_failures
    ALTER COLUMN last_occurred_at SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN last_occurred_at SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_myhome_complex_mapping_failures_status_source
    ON myhome_complex_mapping_failures (status, source_key);

CREATE INDEX IF NOT EXISTS idx_myhome_complex_mapping_failures_source_reason
    ON myhome_complex_mapping_failures (source_key, reason);

CREATE INDEX IF NOT EXISTS idx_myhome_announcement_mapping_failures_status_source
    ON myhome_announcement_mapping_failures (status, source_key);

CREATE INDEX IF NOT EXISTS idx_myhome_announcement_mapping_failures_source_reason
    ON myhome_announcement_mapping_failures (source_key, reason);

CREATE INDEX IF NOT EXISTS idx_lh_announcement_enrichment_failures_status_source
    ON lh_announcement_enrichment_failures (status, source_key);

CREATE INDEX IF NOT EXISTS idx_lh_announcement_enrichment_failures_source_reason
    ON lh_announcement_enrichment_failures (source_key, reason);

-- Applied state from V20260919_04__add_external_failure_lifecycle.sql

ALTER TABLE external_data_collection_failures
    ADD COLUMN IF NOT EXISTS last_occurred_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS occurrence_count INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS recurrence_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS first_execution_id UUID,
    ADD COLUMN IF NOT EXISTS last_execution_id UUID,
    ADD COLUMN IF NOT EXISTS resolved_execution_id UUID;

UPDATE external_data_collection_failures
SET last_occurred_at = occurred_at
WHERE last_occurred_at IS NULL;

ALTER TABLE external_data_collection_failures
    ALTER COLUMN last_occurred_at SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN last_occurred_at SET NOT NULL;

-- Applied state from V20260919_05__create_lh_household_enrichment_failures.sql

CREATE TABLE IF NOT EXISTS lh_household_enrichment_failures (
    id BIGSERIAL PRIMARY KEY,
    source_key VARCHAR(500) NOT NULL,
    area_name VARCHAR(200),
    supply_type_name VARCHAR(200),
    complex_name VARCHAR(500),
    reason VARCHAR(40) NOT NULL,
    detail VARCHAR(1000) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    occurrence_count INTEGER NOT NULL,
    recurrence_count INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    last_resolved_at TIMESTAMP WITH TIME ZONE,
    first_execution_id UUID,
    last_execution_id UUID,
    last_resolved_execution_id UUID
);

CREATE INDEX IF NOT EXISTS idx_lh_household_enrichment_failures_status_source
    ON lh_household_enrichment_failures (status, source_key);

CREATE INDEX IF NOT EXISTS idx_lh_household_enrichment_failures_source_reason
    ON lh_household_enrichment_failures (source_key, reason);

-- Applied state from V20260921_01__add_data_pipeline_schedule_metadata.sql

ALTER TABLE data_pipeline_executions
    ADD COLUMN IF NOT EXISTS execution_trigger VARCHAR(20) DEFAULT 'MANUAL';

ALTER TABLE data_pipeline_executions
    ADD COLUMN IF NOT EXISTS scheduled_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE data_pipeline_executions
    ADD COLUMN IF NOT EXISTS upstream_execution_id UUID;

UPDATE data_pipeline_executions
SET execution_trigger = 'MANUAL'
WHERE execution_trigger IS NULL;

ALTER TABLE data_pipeline_executions
    ALTER COLUMN execution_trigger SET DEFAULT 'MANUAL';

ALTER TABLE data_pipeline_executions
    ALTER COLUMN execution_trigger SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_data_pipeline_execution_upstream
    ON data_pipeline_executions (upstream_execution_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_data_pipeline_execution_type_scheduled_at
    ON data_pipeline_executions (type, scheduled_at)
    WHERE scheduled_at IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_data_pipeline_execution_type_upstream
    ON data_pipeline_executions (type, upstream_execution_id)
    WHERE upstream_execution_id IS NOT NULL;

-- Applied state from V20260921_02__create_data_pipeline_schedule_deferrals.sql

CREATE TABLE IF NOT EXISTS data_pipeline_schedule_deferrals (
    schedule VARCHAR(30) PRIMARY KEY,
    stage VARCHAR(20) NOT NULL,
    scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    reason VARCHAR(40) NOT NULL,
    detail VARCHAR(40),
    observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    next_retry_at TIMESTAMP WITH TIME ZONE NOT NULL,
    resolved_at TIMESTAMP WITH TIME ZONE
);

-- Applied state from V20260921_03__allow_null_schedule_deferral_next_retry_at.sql

ALTER TABLE data_pipeline_schedule_deferrals
    ALTER COLUMN next_retry_at DROP NOT NULL;

-- Reconcile constraints skipped by pre-existing tables.

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'public.road_address_locations'::regclass
          AND conname = 'ck_road_address_location_coordinate_pair'
    ) THEN
        ALTER TABLE public.road_address_locations
            ADD CONSTRAINT ck_road_address_location_coordinate_pair
                CHECK ((x IS NULL AND y IS NULL) OR (x IS NOT NULL AND y IS NOT NULL));
    END IF;
END $$;

DO $$
DECLARE
    child RECORD;
    existing_fk RECORD;
BEGIN
    FOR child IN
        SELECT *
        FROM (VALUES
            ('data_pipeline_execution_completed_steps', 'fk_data_pipeline_completed_step_execution'),
            ('data_pipeline_execution_skipped_steps', 'fk_data_pipeline_skipped_step_execution'),
            ('data_pipeline_execution_partial_failures', 'fk_data_pipeline_execution_partial_failures_execution')
        ) AS children(table_name, constraint_name)
    LOOP
        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint AS constraint_row
            JOIN pg_attribute AS column_row
              ON column_row.attrelid = constraint_row.conrelid
             AND column_row.attnum = constraint_row.conkey[1]
            WHERE constraint_row.conrelid = format('public.%I', child.table_name)::regclass
              AND constraint_row.confrelid = 'public.data_pipeline_executions'::regclass
              AND constraint_row.contype = 'f'
              AND array_length(constraint_row.conkey, 1) = 1
              AND column_row.attname = 'data_pipeline_execution_id'
              AND constraint_row.confdeltype = 'c'
        ) THEN
            FOR existing_fk IN
                SELECT constraint_row.conname
                FROM pg_constraint AS constraint_row
                JOIN pg_attribute AS column_row
                  ON column_row.attrelid = constraint_row.conrelid
                 AND column_row.attnum = constraint_row.conkey[1]
                WHERE constraint_row.conrelid = format('public.%I', child.table_name)::regclass
                  AND constraint_row.confrelid = 'public.data_pipeline_executions'::regclass
                  AND constraint_row.contype = 'f'
                  AND array_length(constraint_row.conkey, 1) = 1
                  AND column_row.attname = 'data_pipeline_execution_id'
            LOOP
                EXECUTE format(
                    'ALTER TABLE public.%I DROP CONSTRAINT %I',
                    child.table_name,
                    existing_fk.conname
                );
            END LOOP;

            EXECUTE format(
                'ALTER TABLE public.%I ADD CONSTRAINT %I '
                    || 'FOREIGN KEY (data_pipeline_execution_id) '
                    || 'REFERENCES public.data_pipeline_executions(id) ON DELETE CASCADE',
                child.table_name,
                child.constraint_name
            );
        END IF;
    END LOOP;
END $$;
