CREATE TABLE ingest_corrections (
    id varchar(250) PRIMARY KEY,
    version bigint NOT NULL DEFAULT 0,
    payload text NOT NULL,
    actor varchar(255) NOT NULL,
    updated_at timestamptz NOT NULL,
    last_failure text
);

CREATE TABLE ingest_correction_changes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target varchar(250) NOT NULL,
    actor varchar(255) NOT NULL,
    occurred_at timestamptz NOT NULL,
    before_value text NOT NULL,
    after_value text NOT NULL
);
CREATE INDEX idx_ingest_correction_changes_target ON ingest_correction_changes(target, id DESC);

ALTER TABLE housing_types ADD COLUMN admin_correction boolean NOT NULL DEFAULT false;
