CREATE TABLE sh_announcement_source (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key varchar(200) NOT NULL UNIQUE,
    seq varchar(100) NOT NULL,
    title text NOT NULL,
    department text NOT NULL,
    registered_date date NOT NULL,
    original_url text NOT NULL,
    list_url text NOT NULL,
    raw_list_html text NOT NULL,
    raw_detail_html text NOT NULL,
    collected_at timestamp with time zone NOT NULL
);
CREATE INDEX idx_sh_announcement_collected_at ON sh_announcement_source (collected_at DESC, id DESC);

ALTER TABLE data_pipeline_executions
    DROP CONSTRAINT IF EXISTS data_pipeline_executions_type_check;

ALTER TABLE data_pipeline_executions
    ADD CONSTRAINT data_pipeline_executions_type_check CHECK (type IN (
        'COMPLEX_COLLECTION', 'COMPLEX_REFINEMENT',
        'ANNOUNCEMENT_COLLECTION', 'ANNOUNCEMENT_REFINEMENT',
        'COMPLEX_SYNC', 'ANNOUNCEMENT_SYNC', 'ANNOUNCEMENT_REGISTRATION', 'SH_ANNOUNCEMENT_COLLECTION'
    ));

ALTER TABLE data_pipeline_executions DROP CONSTRAINT IF EXISTS data_pipeline_executions_current_step_check;
ALTER TABLE data_pipeline_executions ADD CONSTRAINT data_pipeline_executions_current_step_check
    CHECK (current_step IN (
        'COLLECT_MYHOME_COMPLEXES',
        'COLLECT_LH_LEASE_CATALOG',
        'MAP_MYHOME_COMPLEXES',
        'ENRICH_LH_HOUSING_TYPE_HOUSEHOLDS',
        'COLLECT_MYHOME_ANNOUNCEMENTS',
        'COLLECT_LH_ANNOUNCEMENT_CATALOG',
        'COLLECT_LH_ANNOUNCEMENT_SUPPLIES',
        'COLLECT_LH_ANNOUNCEMENT_DETAILS',
        'MAP_MYHOME_ANNOUNCEMENTS',
        'ENRICH_LH_ANNOUNCEMENTS',
        'COLLECT_SH_ANNOUNCEMENTS'
    ));

ALTER TABLE data_pipeline_executions DROP CONSTRAINT IF EXISTS data_pipeline_executions_failed_step_check;
ALTER TABLE data_pipeline_executions ADD CONSTRAINT data_pipeline_executions_failed_step_check
    CHECK (failed_step IN (
        'COLLECT_MYHOME_COMPLEXES',
        'COLLECT_LH_LEASE_CATALOG',
        'MAP_MYHOME_COMPLEXES',
        'ENRICH_LH_HOUSING_TYPE_HOUSEHOLDS',
        'COLLECT_MYHOME_ANNOUNCEMENTS',
        'COLLECT_LH_ANNOUNCEMENT_CATALOG',
        'COLLECT_LH_ANNOUNCEMENT_SUPPLIES',
        'COLLECT_LH_ANNOUNCEMENT_DETAILS',
        'MAP_MYHOME_ANNOUNCEMENTS',
        'ENRICH_LH_ANNOUNCEMENTS',
        'COLLECT_SH_ANNOUNCEMENTS'
    ));

ALTER TABLE data_pipeline_execution_completed_steps DROP CONSTRAINT IF EXISTS data_pipeline_execution_completed_steps_completed_step_check;
ALTER TABLE data_pipeline_execution_completed_steps ADD CONSTRAINT data_pipeline_execution_completed_steps_completed_step_check
    CHECK (completed_step IN (
        'COLLECT_MYHOME_COMPLEXES',
        'COLLECT_LH_LEASE_CATALOG',
        'MAP_MYHOME_COMPLEXES',
        'ENRICH_LH_HOUSING_TYPE_HOUSEHOLDS',
        'COLLECT_MYHOME_ANNOUNCEMENTS',
        'COLLECT_LH_ANNOUNCEMENT_CATALOG',
        'COLLECT_LH_ANNOUNCEMENT_SUPPLIES',
        'COLLECT_LH_ANNOUNCEMENT_DETAILS',
        'MAP_MYHOME_ANNOUNCEMENTS',
        'ENRICH_LH_ANNOUNCEMENTS',
        'COLLECT_SH_ANNOUNCEMENTS'
    ));

ALTER TABLE data_pipeline_execution_skipped_steps DROP CONSTRAINT IF EXISTS data_pipeline_execution_skipped_steps_skipped_step_check;
ALTER TABLE data_pipeline_execution_skipped_steps ADD CONSTRAINT data_pipeline_execution_skipped_steps_skipped_step_check
    CHECK (skipped_step IN (
        'COLLECT_MYHOME_COMPLEXES',
        'COLLECT_LH_LEASE_CATALOG',
        'MAP_MYHOME_COMPLEXES',
        'ENRICH_LH_HOUSING_TYPE_HOUSEHOLDS',
        'COLLECT_MYHOME_ANNOUNCEMENTS',
        'COLLECT_LH_ANNOUNCEMENT_CATALOG',
        'COLLECT_LH_ANNOUNCEMENT_SUPPLIES',
        'COLLECT_LH_ANNOUNCEMENT_DETAILS',
        'MAP_MYHOME_ANNOUNCEMENTS',
        'ENRICH_LH_ANNOUNCEMENTS',
        'COLLECT_SH_ANNOUNCEMENTS'
    ));

ALTER TABLE data_pipeline_execution_partial_failures DROP CONSTRAINT IF EXISTS data_pipeline_execution_partial_fai_partially_failed_step_check;
ALTER TABLE data_pipeline_execution_partial_failures ADD CONSTRAINT data_pipeline_execution_partial_fai_partially_failed_step_check
    CHECK (partially_failed_step IN (
        'COLLECT_MYHOME_COMPLEXES',
        'COLLECT_LH_LEASE_CATALOG',
        'MAP_MYHOME_COMPLEXES',
        'ENRICH_LH_HOUSING_TYPE_HOUSEHOLDS',
        'COLLECT_MYHOME_ANNOUNCEMENTS',
        'COLLECT_LH_ANNOUNCEMENT_CATALOG',
        'COLLECT_LH_ANNOUNCEMENT_SUPPLIES',
        'COLLECT_LH_ANNOUNCEMENT_DETAILS',
        'MAP_MYHOME_ANNOUNCEMENTS',
        'ENRICH_LH_ANNOUNCEMENTS',
        'COLLECT_SH_ANNOUNCEMENTS'
    ));

ALTER TABLE external_data_collection_failures DROP CONSTRAINT IF EXISTS external_data_collection_failures_source_check;
ALTER TABLE external_data_collection_failures ADD CONSTRAINT external_data_collection_failures_source_check
    CHECK (source IN (
        'MYHOME_COMPLEX',
        'MYHOME_ANNOUNCEMENT',
        'LH_LEASE_CATALOG',
        'LH_ANNOUNCEMENT_CATALOG',
        'LH_ANNOUNCEMENT_DETAIL',
        'LH_ANNOUNCEMENT_SUPPLY',
        'SH_ANNOUNCEMENT'
    ));
