CREATE TABLE lh_announcement_query_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    source VARCHAR(50) NOT NULL,
    pan_id VARCHAR(100) NOT NULL,
    query_hash VARCHAR(64) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    request_description TEXT NOT NULL,
    collected_at TIMESTAMPTZ NOT NULL,
    verified_empty BOOLEAN NOT NULL,
    last_collection_record_id UUID NOT NULL REFERENCES source_collection_records(id),
    UNIQUE(source, query_hash)
);
CREATE INDEX idx_lh_announcement_query_sources_lookup
    ON lh_announcement_query_sources(source, pan_id, request_hash);
CREATE TABLE lh_announcement_query_parameters (
    source_id BIGINT NOT NULL REFERENCES lh_announcement_query_sources(id),
    parameter_name VARCHAR(100) NOT NULL,
    parameter_value TEXT NOT NULL,
    PRIMARY KEY(source_id, parameter_name)
);
CREATE TABLE lh_announcement_supply_rows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL REFERENCES lh_announcement_query_sources(id),
    source_order INTEGER NOT NULL CHECK (source_order >= 0),
    complex_label TEXT,
    type_name TEXT,
    exclusive_area TEXT,
    supply_area TEXT,
    total_unit_count TEXT,
    supplied_unit_count TEXT,
    deposit_text TEXT,
    monthly_rent_text TEXT,
    UNIQUE(source_id, source_order)
);
CREATE TABLE lh_announcement_detail_rows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL REFERENCES lh_announcement_query_sources(id),
    source_order INTEGER NOT NULL CHECK (source_order >= 0),
    dataset_type TEXT,
    complex_name TEXT,
    address TEXT,
    detail_address TEXT,
    total_unit_count TEXT,
    heating_description TEXT,
    exclusive_area_range TEXT,
    expected_move_in_year_month TEXT,
    guidance_text TEXT,
    application_period TEXT,
    application_begin_date TEXT,
    application_end_date TEXT,
    winner_announcement_date TEXT,
    document_target_announcement_date TEXT,
    document_submission_begin_date TEXT,
    document_submission_end_date TEXT,
    contract_begin_date TEXT,
    contract_end_date TEXT,
    reception_address TEXT,
    reception_detail_address TEXT,
    operation_begin TEXT,
    operation_end TEXT,
    phone TEXT,
    reception_guidance TEXT,
    kind TEXT,
    name TEXT,
    url TEXT,
    attachment_complex_name TEXT,
    correction_reason TEXT,
    etc_contents TEXT,
    UNIQUE(source_id, source_order)
);
