CREATE TABLE lh_announcement_catalog_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    source_key VARCHAR(200) NOT NULL UNIQUE,
    pan_id TEXT,
    connection_system_division_code TEXT,
    upper_announcement_type_code TEXT,
    announcement_type_code TEXT,
    supply_info_type_code TEXT,
    announcement_name TEXT,
    status TEXT,
    notice_date TEXT,
    publication_date TEXT,
    closing_date TEXT,
    detail_url TEXT,
    mobile_detail_url TEXT,
    raw_payload TEXT NOT NULL,
    query_start_date TEXT NOT NULL,
    query_end_date TEXT NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL,
    collected_at TIMESTAMPTZ NOT NULL,
    present_in_latest_catalog BOOLEAN NOT NULL,
    last_collection_record_id UUID NOT NULL REFERENCES source_collection_records(id)
);
CREATE INDEX idx_lh_announcement_catalog_entries_pan_id ON lh_announcement_catalog_entries(pan_id);

CREATE TABLE lh_announcement_catalog_write_lock (
    id BIGINT PRIMARY KEY CHECK (id = 1)
);
INSERT INTO lh_announcement_catalog_write_lock(id) VALUES (1);
