CREATE TABLE admin_announcement_imports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schema_version VARCHAR(64) NOT NULL,
    original_url VARCHAR(255) NOT NULL,
    source_document_id VARCHAR(255),
    json_hash VARCHAR(64) NOT NULL,
    original_json TEXT NOT NULL,
    registered_by VARCHAR(255) NOT NULL,
    registered_at TIMESTAMP WITH TIME ZONE NOT NULL,
    announcement_id BIGINT NOT NULL,
    CONSTRAINT fk_admin_announcement_import_announcement
        FOREIGN KEY (announcement_id) REFERENCES announcements (id),
    CONSTRAINT uk_admin_announcement_import_hash UNIQUE (json_hash),
    CONSTRAINT uk_admin_announcement_import_source_document UNIQUE (source_document_id),
    CONSTRAINT uk_admin_announcement_import_announcement UNIQUE (announcement_id)
);
