ALTER TABLE announcements
    ADD COLUMN application_schedule_reviewed BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN lh_pan_id_reviewed BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN revision_evidence_url VARCHAR(2000),
    ADD COLUMN previous_lh_pan_id VARCHAR(255);

CREATE TABLE announcement_application_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    announcement_id BIGINT NOT NULL REFERENCES announcements (id),
    housing_complex_id BIGINT REFERENCES housing_complexes (id),
    supply_rank VARCHAR(255),
    state VARCHAR(20) NOT NULL CHECK (state IN ('CONFIRMED', 'CONDITIONAL')),
    application_condition VARCHAR(1000),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    start_time TIME,
    end_time TIME,
    source_url VARCHAR(2000) NOT NULL,
    source_page INTEGER NOT NULL CHECK (source_page > 0),
    CHECK (end_date >= start_date),
    CHECK ((start_time IS NULL) = (end_time IS NULL)),
    CHECK (start_date <> end_date OR end_time >= start_time),
    CHECK (state <> 'CONDITIONAL' OR NULLIF(TRIM(application_condition), '') IS NOT NULL)
);

CREATE INDEX idx_application_schedules_announcement_dates
    ON announcement_application_schedules (announcement_id, start_date, end_date);
