CREATE TABLE source_collection_records (
    id uuid PRIMARY KEY,
    version bigint NOT NULL,
    execution_id uuid,
    source varchar(40) NOT NULL,
    started_at timestamp with time zone NOT NULL,
    finished_at timestamp with time zone,
    status varchar(20) NOT NULL CHECK (status IN ('RUNNING', 'SUCCESS', 'FAILED')),
    stored_row_count integer NOT NULL CHECK (stored_row_count >= 0),
    error_type varchar(120),
    failure_reason varchar(1000),
    CHECK (finished_at >= started_at),
    CHECK ((status = 'RUNNING' AND finished_at IS NULL AND stored_row_count = 0
            AND error_type IS NULL AND failure_reason IS NULL)
        OR (status = 'SUCCESS' AND finished_at IS NOT NULL AND error_type IS NULL AND failure_reason IS NULL)
        OR (status = 'FAILED' AND finished_at IS NOT NULL AND stored_row_count = 0
            AND error_type IS NOT NULL AND failure_reason IS NOT NULL))
);

CREATE TABLE source_collection_record_parameters (
    record_id uuid NOT NULL REFERENCES source_collection_records(id),
    parameter_name varchar(100) NOT NULL,
    parameter_value varchar(500) NOT NULL,
    PRIMARY KEY (record_id, parameter_name)
);

CREATE TABLE myhome_announcement_source_bundles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version bigint NOT NULL,
    pblanc_id varchar(100) NOT NULL UNIQUE,
    last_collection_record_id uuid NOT NULL REFERENCES source_collection_records(id)
);

CREATE TABLE myhome_announcement_source_rows (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id bigint NOT NULL REFERENCES myhome_announcement_source_bundles(id),
    collection_record_id uuid NOT NULL REFERENCES source_collection_records(id),
    request_supply_type_code varchar(2) NOT NULL,
    collected_at timestamp with time zone NOT NULL,
    source_order integer NOT NULL CHECK (source_order >= 0),
    pblanc_id varchar(100) NOT NULL,
    house_sn integer NOT NULL,
    sttus_nm text,
    pblanc_nm text,
    suply_instt_nm text,
    house_ty_nm text,
    suply_ty_nm text,
    before_pblanc_id text,
    rcrit_pblanc_de text,
    przwner_presnatn_de text,
    begin_de text,
    end_de text,
    refrnc text,
    url text,
    pc_url text,
    mobile_url text,
    hsmp_nm text,
    brtc_nm text,
    signgu_nm text,
    full_adres text,
    rn_code_nm text,
    refrn_legaldong_nm text,
    pnu text,
    heat_mthd_nm text,
    tot_hshld_co text,
    sum_suply_co integer,
    rent_gtn bigint,
    enty bigint,
    surlus bigint,
    mt_rntchrg bigint,
    UNIQUE (source_id, request_supply_type_code, source_order)
);
