CREATE TABLE public.lh_announcement_catalog_source (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key varchar(200) NOT NULL UNIQUE,
    pan_id varchar(100) NOT NULL,
    connection_system_division_code varchar(10) NOT NULL,
    upper_announcement_type_code varchar(10) NOT NULL,
    announcement_type_code varchar(10) NOT NULL,
    supply_info_type_code varchar(10) NOT NULL,
    content_fingerprint varchar(64) NOT NULL,
    raw_payload text NOT NULL,
    changed_at timestamp with time zone NOT NULL,
    collected_at timestamp with time zone NOT NULL
);
CREATE INDEX idx_lh_announcement_catalog_pan_id ON public.lh_announcement_catalog_source (pan_id);

ALTER TABLE public.data_pipeline_executions DROP CONSTRAINT IF EXISTS data_pipeline_executions_current_step_check;
ALTER TABLE public.data_pipeline_executions ADD CONSTRAINT data_pipeline_executions_current_step_check
    CHECK (current_step IN (
        'COLLECT_MYHOME_COMPLEXES',
        'COLLECT_LH_LEASE_CATALOG',
        'MAP_MYHOME_COMPLEXES',
        'ENRICH_LH_HOUSING_TYPE_HOUSEHOLDS',
        'COLLECT_MYHOME_ANNOUNCEMENTS',
        'COLLECT_LH_ANNOUNCEMENT_CATALOG',
        'COLLECT_LH_ANNOUNCEMENT_SUPPLIES',
        'COLLECT_LH_ANNOUNCEMENT_DETAILS',
        'MAP_MYHOME_ANNOUNCEMENTS',
        'ENRICH_LH_ANNOUNCEMENTS'
    ));

ALTER TABLE public.data_pipeline_executions DROP CONSTRAINT IF EXISTS data_pipeline_executions_failed_step_check;
ALTER TABLE public.data_pipeline_executions ADD CONSTRAINT data_pipeline_executions_failed_step_check
    CHECK (failed_step IN (
        'COLLECT_MYHOME_COMPLEXES',
        'COLLECT_LH_LEASE_CATALOG',
        'MAP_MYHOME_COMPLEXES',
        'ENRICH_LH_HOUSING_TYPE_HOUSEHOLDS',
        'COLLECT_MYHOME_ANNOUNCEMENTS',
        'COLLECT_LH_ANNOUNCEMENT_CATALOG',
        'COLLECT_LH_ANNOUNCEMENT_SUPPLIES',
        'COLLECT_LH_ANNOUNCEMENT_DETAILS',
        'MAP_MYHOME_ANNOUNCEMENTS',
        'ENRICH_LH_ANNOUNCEMENTS'
    ));

ALTER TABLE public.data_pipeline_execution_completed_steps DROP CONSTRAINT IF EXISTS data_pipeline_execution_completed_steps_completed_step_check;
ALTER TABLE public.data_pipeline_execution_completed_steps ADD CONSTRAINT data_pipeline_execution_completed_steps_completed_step_check
    CHECK (completed_step IN (
        'COLLECT_MYHOME_COMPLEXES',
        'COLLECT_LH_LEASE_CATALOG',
        'MAP_MYHOME_COMPLEXES',
        'ENRICH_LH_HOUSING_TYPE_HOUSEHOLDS',
        'COLLECT_MYHOME_ANNOUNCEMENTS',
        'COLLECT_LH_ANNOUNCEMENT_CATALOG',
        'COLLECT_LH_ANNOUNCEMENT_SUPPLIES',
        'COLLECT_LH_ANNOUNCEMENT_DETAILS',
        'MAP_MYHOME_ANNOUNCEMENTS',
        'ENRICH_LH_ANNOUNCEMENTS'
    ));

ALTER TABLE public.data_pipeline_execution_skipped_steps DROP CONSTRAINT IF EXISTS data_pipeline_execution_skipped_steps_skipped_step_check;
ALTER TABLE public.data_pipeline_execution_skipped_steps ADD CONSTRAINT data_pipeline_execution_skipped_steps_skipped_step_check
    CHECK (skipped_step IN (
        'COLLECT_MYHOME_COMPLEXES',
        'COLLECT_LH_LEASE_CATALOG',
        'MAP_MYHOME_COMPLEXES',
        'ENRICH_LH_HOUSING_TYPE_HOUSEHOLDS',
        'COLLECT_MYHOME_ANNOUNCEMENTS',
        'COLLECT_LH_ANNOUNCEMENT_CATALOG',
        'COLLECT_LH_ANNOUNCEMENT_SUPPLIES',
        'COLLECT_LH_ANNOUNCEMENT_DETAILS',
        'MAP_MYHOME_ANNOUNCEMENTS',
        'ENRICH_LH_ANNOUNCEMENTS'
    ));

ALTER TABLE public.data_pipeline_execution_partial_failures DROP CONSTRAINT IF EXISTS data_pipeline_execution_partial_fai_partially_failed_step_check;
ALTER TABLE public.data_pipeline_execution_partial_failures ADD CONSTRAINT data_pipeline_execution_partial_fai_partially_failed_step_check
    CHECK (partially_failed_step IN (
        'COLLECT_MYHOME_COMPLEXES',
        'COLLECT_LH_LEASE_CATALOG',
        'MAP_MYHOME_COMPLEXES',
        'ENRICH_LH_HOUSING_TYPE_HOUSEHOLDS',
        'COLLECT_MYHOME_ANNOUNCEMENTS',
        'COLLECT_LH_ANNOUNCEMENT_CATALOG',
        'COLLECT_LH_ANNOUNCEMENT_SUPPLIES',
        'COLLECT_LH_ANNOUNCEMENT_DETAILS',
        'MAP_MYHOME_ANNOUNCEMENTS',
        'ENRICH_LH_ANNOUNCEMENTS'
    ));

ALTER TABLE public.external_data_collection_failures DROP CONSTRAINT IF EXISTS external_data_collection_failures_source_check;
ALTER TABLE public.external_data_collection_failures ADD CONSTRAINT external_data_collection_failures_source_check
    CHECK (source IN (
        'MYHOME_COMPLEX',
        'MYHOME_ANNOUNCEMENT',
        'LH_LEASE_CATALOG',
        'LH_ANNOUNCEMENT_CATALOG',
        'LH_ANNOUNCEMENT_DETAIL',
        'LH_ANNOUNCEMENT_SUPPLY'
    ));

ALTER TABLE public.lh_announcement_collection_checkpoints DROP CONSTRAINT IF EXISTS lh_announcement_collection_checkpoints_source_check;
ALTER TABLE public.lh_announcement_collection_checkpoints ADD CONSTRAINT lh_announcement_collection_checkpoints_source_check
    CHECK (source IN (
        'MYHOME_COMPLEX',
        'MYHOME_ANNOUNCEMENT',
        'LH_LEASE_CATALOG',
        'LH_ANNOUNCEMENT_CATALOG',
        'LH_ANNOUNCEMENT_DETAIL',
        'LH_ANNOUNCEMENT_SUPPLY'
    ));

ALTER TABLE public.lh_announcement_collection_links DROP CONSTRAINT IF EXISTS lh_announcement_collection_links_source_check;
ALTER TABLE public.lh_announcement_collection_links ADD CONSTRAINT lh_announcement_collection_links_source_check
    CHECK (source IN (
        'MYHOME_COMPLEX',
        'MYHOME_ANNOUNCEMENT',
        'LH_LEASE_CATALOG',
        'LH_ANNOUNCEMENT_CATALOG',
        'LH_ANNOUNCEMENT_DETAIL',
        'LH_ANNOUNCEMENT_SUPPLY'
    ));
