CREATE TABLE verified_lh_supply_replacements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_hash VARCHAR(64) NOT NULL,
    proposed_fingerprint VARCHAR(64) NOT NULL,
    evidence_url VARCHAR(2000) NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    approved_by VARCHAR(255) NOT NULL,
    approved_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ
);

CREATE INDEX idx_verified_lh_supply_replacements_pending
    ON verified_lh_supply_replacements (request_hash, proposed_fingerprint)
    WHERE consumed_at IS NULL AND revoked_at IS NULL;

ALTER TABLE supply_targets ADD COLUMN lh_amount_preserved_reason VARCHAR(50);
