ALTER TABLE housing_complexes
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN admin_modified BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN admin_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN source_review_required BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN admin_updated_at TIMESTAMPTZ;
ALTER TABLE announcements
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN admin_modified BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN admin_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN source_review_required BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN admin_updated_at TIMESTAMPTZ;
ALTER TABLE supply_rows ADD COLUMN admin_modified BOOLEAN NOT NULL DEFAULT FALSE;
CREATE TABLE admin_data_changes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_type VARCHAR(30) NOT NULL,
    resource_id BIGINT NOT NULL,
    action VARCHAR(30) NOT NULL,
    actor VARCHAR(255) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    before_value TEXT NOT NULL,
    after_value TEXT NOT NULL
);
CREATE INDEX idx_admin_data_changes_resource ON admin_data_changes(resource_type, resource_id, id DESC);
