CREATE TABLE myhome_complex_source_regions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version bigint NOT NULL,
    province_code varchar(2) NOT NULL,
    district_code varchar(3) NOT NULL,
    collected_at timestamp with time zone NOT NULL,
    last_collection_record_id uuid NOT NULL REFERENCES source_collection_records(id),
    UNIQUE (province_code, district_code)
);

CREATE TABLE myhome_complex_source_bundles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version bigint NOT NULL,
    hsmp_sn bigint NOT NULL UNIQUE CHECK (hsmp_sn > 0),
    region_id bigint NOT NULL REFERENCES myhome_complex_source_regions(id)
);

CREATE INDEX idx_myhome_complex_bundles_region ON myhome_complex_source_bundles(region_id);

CREATE TABLE myhome_complex_source_rows (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id bigint NOT NULL REFERENCES myhome_complex_source_bundles(id),
    source_order integer NOT NULL CHECK (source_order >= 0),
    hsmp_sn bigint NOT NULL,
    instt_nm text,
    brtc_code text,
    brtc_nm text,
    signgu_code text,
    signgu_nm text,
    hsmp_nm text,
    rn_adres text,
    pnu text,
    compet_de text,
    hshld_co integer,
    suply_ty_nm text,
    style_nm text,
    suply_prvuse_ar numeric,
    suply_cmnuse_ar numeric,
    house_ty_nm text,
    heat_mthd_detail_nm text,
    buld_stle_nm text,
    elvtr_instl_at_nm text,
    parkng_co integer,
    bass_rent_gtn bigint,
    bass_mt_rntchrg bigint,
    bass_cnvrs_gtn_lmt bigint,
    UNIQUE (source_id, source_order)
);
