CREATE TABLE feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(2000) NOT NULL CHECK (length(btrim(content)) > 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_feedback_created_at_id ON feedback (created_at DESC, id DESC);
