CREATE TABLE announcement_views (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    announcement_id bigint NOT NULL REFERENCES announcements(id) ON DELETE CASCADE,
    viewer_id uuid NOT NULL,
    viewed_on date NOT NULL,
    CONSTRAINT uk_announcement_view_browser UNIQUE (announcement_id, viewer_id)
);
