CREATE TABLE lh_lease_catalog_source_bundles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version bigint NOT NULL,
    scope_key varchar(20) NOT NULL UNIQUE,
    collected_at timestamp with time zone NOT NULL,
    last_collection_record_id uuid NOT NULL REFERENCES source_collection_records(id)
);

CREATE TABLE lh_lease_catalog_source_rows (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id bigint NOT NULL REFERENCES lh_lease_catalog_source_bundles(id),
    source_order integer NOT NULL CHECK (source_order >= 0),
    area_name text,
    supply_type_name text,
    complex_label text,
    complex_total_unit_count text,
    exclusive_area text,
    total_unit_count text,
    deposit_text text,
    monthly_rent_text text,
    UNIQUE (source_id, source_order)
);
