package com.toadzip.backend.ingest.pipeline.repository;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import javax.sql.DataSource;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.datasource.init.ScriptUtils;
import org.springframework.test.context.ActiveProfiles;

@SpringBootTest
@ActiveProfiles("test")
class DataPipelineSyncMigrationTest {

    @Autowired
    private DataSource dataSource;

    @Test
    void 기존_네_유형을_보존하고_통합_유형만_추가로_허용한다() throws Exception {
        try (Connection connection = dataSource.getConnection(); var statement = connection.createStatement()) {
            statement.execute("CREATE SCHEMA pipeline_sync_migration_test");
            statement.execute("SET search_path TO pipeline_sync_migration_test");
            try {
                statement.execute("""
                        CREATE TABLE data_pipeline_executions (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            type VARCHAR(40) NOT NULL,
                            report TEXT NOT NULL DEFAULT '기존 보고서',
                            CONSTRAINT data_pipeline_executions_type_check CHECK (type IN (
                                'COMPLEX_COLLECTION', 'COMPLEX_REFINEMENT',
                                'ANNOUNCEMENT_COLLECTION', 'ANNOUNCEMENT_REFINEMENT'
                            ))
                        )
                        """);
                for (String type : List.of("COMPLEX_COLLECTION", "COMPLEX_REFINEMENT",
                        "ANNOUNCEMENT_COLLECTION", "ANNOUNCEMENT_REFINEMENT")) {
                    insert(connection, type);
                }
                assertThatThrownBy(() -> insert(connection, "ANNOUNCEMENT_SYNC"))
                        .isInstanceOf(SQLException.class);

                ScriptUtils.executeSqlScript(connection, new ClassPathResource(
                        "db/migration/V20260930_01__allow_combined_ingest_pipelines.sql"));

                insert(connection, "COMPLEX_SYNC");
                insert(connection, "ANNOUNCEMENT_SYNC");
                assertThatThrownBy(() -> insert(connection, "UNKNOWN"))
                        .isInstanceOf(SQLException.class);
                try (var rows = statement.executeQuery("SELECT count(*) FROM data_pipeline_executions")) {
                    rows.next();
                    assertThat(rows.getInt(1)).isEqualTo(6);
                }
                try (var rows = statement.executeQuery(
                        "SELECT count(*) FROM data_pipeline_executions WHERE id <= 4 AND report = '기존 보고서'")) {
                    rows.next();
                    assertThat(rows.getInt(1)).isEqualTo(4);
                }
            }
            finally {
                statement.execute("RESET search_path");
                statement.execute("DROP SCHEMA pipeline_sync_migration_test CASCADE");
            }
        }
    }

    private void insert(Connection connection, String type) throws SQLException {
        try (var statement = connection.prepareStatement("INSERT INTO data_pipeline_executions (type) VALUES (?)")) {
            statement.setString(1, type);
            statement.executeUpdate();
        }
    }
}
