spring:
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    com.toadzip.backend: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

app:
  admin:
    bootstrap:
      enabled: ${ADMIN_BOOTSTRAP_ENABLED:false}
      login-identifier: ${ADMIN_LOGIN_IDENTIFIER:}
      password: ${ADMIN_PASSWORD:}
