global:
  scrape_interval: 15s

scrape_configs:
  - job_name: backend
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - 10.0.0.181:8081
        labels:
          environment: dev
          application: toadzip-backend
      - targets:
          - 10.0.0.236:8081
        labels:
          environment: prod
          application: toadzip-backend
